import { Crosshair, MapPin, Search } from 'lucide-react'
import Card from '../../../../components/ui/Card'

export default function AgriStoreSearch({ draft, onChange, onSearch }) {
  return <Card className="p-3 xl:flex xl:min-h-[90px] xl:items-center"><form onSubmit={event => { event.preventDefault(); onSearch() }} className="grid w-full gap-2.5 sm:grid-cols-2 xl:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)_minmax(0,1.55fr)_minmax(0,.8fr)_138px] xl:items-end">
    <label className="min-w-0 text-xs font-medium text-slate-900">Your Location<div className="mt-1 flex h-[40px] items-center rounded-lg border border-slate-200 bg-white px-2"><MapPin className="size-4 shrink-0 text-slate-500" /><input value={draft.location} onChange={event => onChange({ ...draft, location: event.target.value })} className="min-w-0 flex-1 px-2 text-xs outline-none" aria-label="Your location" /><button type="button" aria-label="Use Varanasi as current location" onClick={() => onChange({ ...draft, location: 'Varanasi, Uttar Pradesh' })}><Crosshair className="size-4 text-slate-700" /></button></div></label>
    <label className="min-w-0 text-xs font-medium text-slate-900">Product Type<select value={draft.productType} onChange={event => onChange({ ...draft, productType: event.target.value })} className="mt-1 h-[40px] w-full rounded-lg border border-slate-200 bg-white px-2 text-xs text-slate-700"><option value="all">All Products</option><option>Fungicide</option><option>Fertilizer</option><option>Seeds</option><option>Bio-pesticide</option></select></label>
    <label className="min-w-0 text-xs font-medium text-slate-900">Search Store or Product<div className="mt-1 flex h-[40px] items-center rounded-lg border border-slate-200 bg-white px-2"><Search className="size-4 shrink-0 text-slate-500" /><input value={draft.query} onChange={event => onChange({ ...draft, query: event.target.value })} placeholder="e.g. urea, DAP, pesticide, store name" className="min-w-0 flex-1 px-2 text-xs outline-none" /></div></label>
    <label className="min-w-0 text-xs font-medium text-slate-900">Distance<select value={draft.distance} onChange={event => onChange({ ...draft, distance: event.target.value })} className="mt-1 h-[40px] w-full rounded-lg border border-slate-200 bg-white px-2 text-xs text-slate-700"><option value="10">Within 10 km</option><option value="5">Within 5 km</option><option value="3">Within 3 km</option><option value="2">Within 2 km</option></select></label>
    <button type="submit" className="flex h-[40px] items-center justify-center gap-2 rounded-lg bg-emerald-700 px-4 text-sm font-medium text-white hover:bg-emerald-800 sm:col-span-2 xl:col-span-1"><Search className="size-4" />Search</button>
  </form></Card>
}
