import { CircleCheck, Package } from 'lucide-react'
import Card from '../../../../components/ui/Card'
import { timelineLabels } from '../data/orders.mock'

export default function DispatchFulfillment({ order }) {
  if (!order) return null
  const delivered = order.deliveryStatus === 'delivered'
  return <Card className="min-h-[415px] p-4 xl:flex xl:flex-col xl:justify-between"><h2 className="mb-3 flex items-center gap-2.5 text-base font-bold text-slate-900"><span className="grid size-7 place-items-center rounded-md bg-emerald-800 text-white"><Package className="size-4" /></span>Dispatch & Fulfillment</h2><ol className="ml-1">{timelineLabels.map((label, index) => { const complete = Boolean(order.timeline[index]); return <li key={label} className="relative flex min-h-[62px] gap-4 last:min-h-[50px]">{index < timelineLabels.length - 1 && <span className={`absolute left-[11px] top-6 h-[42px] w-0.5 ${complete ? 'bg-emerald-300' : 'bg-slate-200'}`} />}<span className={`relative z-10 grid size-6 shrink-0 place-items-center rounded-full ${complete ? 'bg-emerald-600 text-white' : 'bg-slate-200 text-slate-500'}`}><CircleCheck className="size-4" /></span><div><p className={`text-xs font-medium ${complete ? 'text-slate-900' : 'text-slate-500'}`}>{label}</p><p className="mt-0.5 text-[11px] text-slate-500">{order.timeline[index] || 'Awaiting update'}</p></div></li> })}</ol><div className={`mt-2 flex items-center gap-3 rounded-lg p-3 ${delivered ? 'bg-emerald-50' : 'bg-slate-50'}`}><span className={`grid size-9 shrink-0 place-items-center rounded-full ${delivered ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600'}`}><CircleCheck className="size-5" /></span><div><p className="text-xs font-semibold text-slate-900">{delivered ? 'Order delivered successfully!' : 'Order is being fulfilled'}</p><p className="mt-0.5 text-[11px] text-slate-500">{delivered ? 'The customer has received the order.' : 'Follow the steps above for the latest status.'}</p></div></div></Card>
}
