import { EllipsisVertical, Funnel, ReceiptIndianRupee } from 'lucide-react'
import Card from '../../../../components/ui/Card'
import ProductImage from '../../products/components/ProductImage'
import ConsumerAvatar from './ConsumerAvatar'
import OrderStatusBadge from './OrderStatusBadge'
import OrderMobileCard from './OrderMobileCard'

const selectClass = 'h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs text-slate-700 outline-none focus:border-emerald-600'

export default function OrdersTable({ orders, onView, status, onStatusChange, dateRange, onDateRangeChange, onFilter }) {
  return <Card className="min-w-0 p-4"><div className="flex min-h-[60px] flex-col gap-3 md:flex-row md:items-start md:justify-between"><div className="flex items-start gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-emerald-800 text-white"><ReceiptIndianRupee className="size-5" /></span><div><h2 className="text-lg font-bold leading-tight text-slate-900">All Orders</h2><p className="text-xs text-slate-500">View and manage all your customer orders.</p></div></div><div className="flex flex-wrap items-center gap-2"><label><span className="sr-only">Order status</span><select value={status} onChange={event => onStatusChange(event.target.value)} className={selectClass}><option value="all">All Orders</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="processing">Processing</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option></select></label><label><span className="sr-only">Date range</span><select value={dateRange} onChange={event => onDateRangeChange(event.target.value)} className={selectClass}><option value="30">Last 30 Days</option><option value="7">Last 7 Days</option><option value="3">Last 3 Days</option><option value="all">All Dates</option></select></label><button type="button" onClick={onFilter} className="inline-flex h-9 items-center justify-center gap-2 rounded-lg bg-emerald-700 px-5 text-xs font-semibold text-white hover:bg-emerald-800"><Funnel className="size-4" />Filter</button></div></div>
    <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1080px] table-fixed text-left text-[11px]"><colgroup><col className="w-[8%]" /><col className="w-[14%]" /><col className="w-[16%]" /><col className="w-[8%]" /><col className="w-[8%]" /><col className="w-[12%]" /><col className="w-[12%]" /><col className="w-[11%]" /><col className="w-[11%]" /></colgroup><thead><tr className="h-9 border-b border-slate-200 bg-slate-50 text-[10px] font-medium text-slate-700"><th className="pl-3">Order ID</th><th>Consumer</th><th>Products</th><th>Quantity</th><th>Amount</th><th>Delivery Status</th><th>Payment Status</th><th>Order Date</th><th>Actions</th></tr></thead><tbody>{orders.map(order => <tr key={order.id} className="h-[62px] border-b border-slate-200/80 last:border-0"><td className="pl-3 font-semibold whitespace-nowrap text-slate-900">#{order.id}</td><td><div className="flex items-center gap-2"><ConsumerAvatar consumer={order.consumer} className="size-8" /><div className="min-w-0"><p className="truncate font-medium text-slate-900">{order.consumer.name}</p><p className="text-[10px] text-slate-500">{order.consumer.location}</p></div></div></td><td><div className="flex items-center gap-2"><ProductImage product={order.product} className="size-10" /><div className="min-w-0"><p className="truncate font-medium text-slate-900">{order.product.name}</p><p className="text-[10px] text-slate-500">{order.product.packageSize}</p></div></div></td><td className="text-slate-700">{order.quantity}</td><td className="font-semibold whitespace-nowrap text-slate-900">₹ {order.amount.toLocaleString('en-IN')}</td><td><OrderStatusBadge status={order.deliveryStatus} /></td><td><OrderStatusBadge status={order.paymentStatus} type="payment" /></td><td className="whitespace-nowrap text-slate-500">{order.dateLabel}</td><td><div className="flex items-center gap-2"><button type="button" onClick={() => onView(order.id)} className="rounded-lg border border-slate-200 px-4 py-1.5 text-xs font-semibold text-slate-700 hover:border-emerald-300">View</button><button type="button" aria-label={`More actions for order ${order.id}`} className="rounded-lg p-1 hover:bg-slate-100"><EllipsisVertical className="size-4" /></button></div></td></tr>)}</tbody></table></div>
    <div className="grid gap-2 md:hidden">{orders.map(order => <OrderMobileCard key={order.id} order={order} onView={onView} />)}</div>
    {orders.length === 0 && <p className="py-12 text-center text-sm text-slate-500">No orders match these filters.</p>}
  </Card>
}
