import { ArrowLeft, ArrowRight, Award, BadgeCheck, CalendarDays, Check, ChevronRight, ClipboardCheck, ExternalLink, FlaskConical, House, Leaf, MapPin, PackageCheck, QrCode, ShieldCheck, Sprout, Truck, UsersRound, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { routes } from '../../../../config/routes'
import ProductPhoto from '../ProductPhoto'

const card = 'min-w-0 rounded-xl border border-[#dfe9e8] bg-white p-3 shadow-[0_2px_12px_rgba(21,85,65,0.025)]'

function SectionHeading({ icon: Icon, children, action }) {
  return <div className="mb-3 flex min-h-6 items-center justify-between gap-2"><h2 className="flex items-center gap-2 text-[16px] font-bold text-[#172033]"><Icon className="size-6 shrink-0 text-emerald-800" fill={Icon === UsersRound ? 'currentColor' : 'none'} />{children}</h2>{action}</div>
}

export function FarmPassportHeader() {
  return <header className="relative isolate min-h-[138px] overflow-hidden bg-[#f4fcf6] px-4 py-3 sm:px-6"><div className="absolute inset-0 -z-20 bg-[url('/images/dashboard/farmer-hero.png')] bg-cover bg-[center_56%]" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-white via-white/90 to-white/30" /><ProductPhoto tile={0} alt="Organic Basmati Rice" className="absolute inset-y-0 right-0 z-0 hidden h-full w-[240px] [mask-image:linear-gradient(to_right,transparent,black_20%)] lg:block" /><div className="relative z-10"><Link to={routes.consumer.products} className="inline-flex items-center gap-1 text-xs font-medium text-emerald-900 hover:underline"><ArrowLeft size={16} />Back to Products</Link><h1 className="mt-3 flex items-center gap-2 text-[32px] font-extrabold leading-tight tracking-tight text-slate-950 sm:text-[38px]">Farm Passport <Leaf className="size-7 fill-[#66b847] text-emerald-700" /></h1><p className="max-w-[650px] text-[14px] text-[#283653]">Complete journey from our farm to your home. Real people. Real processes. Real food.</p></div><div aria-hidden="true" className="absolute right-[19%] top-7 z-10 hidden -rotate-12 font-serif text-[18px] italic leading-5 text-[#14274c] xl:block">Know<br />Your Food<br />Know Your Farmer<span className="mt-1 block h-0.5 rotate-[-8deg] rounded-full bg-emerald-700" /></div><p aria-hidden="true" className="absolute right-4 top-6 z-10 hidden text-sm font-bold leading-4 text-[#103c29] 2xl:block">Pure Food<br />Transparent<br />Journey<br />Brighter<br />Futures</p></header>
}

export function PassportProductCard({ product }) {
  const details = [['Batch ID', product.batchId], ['Harvest Date', product.harvestDate], ['Variety', product.variety], ['Packaging Date', product.packagingDate], ['Net Weight', product.netWeight], ['Best Before', product.bestBefore]]
  return <section id="passport-product" className={`${card} flex flex-col gap-4 sm:flex-row sm:items-stretch`}><div className="relative h-[190px] shrink-0 sm:h-auto sm:w-[32%]"><ProductPhoto tile={product.imageTile} alt={product.name} className="size-full rounded-lg" /><span className="absolute left-2 top-2 rounded-md bg-emerald-700 px-2 py-1 text-xs font-semibold text-white">{product.badge}</span></div><div className="min-w-0 flex-1"><h2 className="text-[19px] font-bold text-[#172033]">{product.name}</h2><div className="mt-2 flex flex-wrap gap-2">{product.tags.map((tag, index) => <span key={tag} className={`rounded-md px-2 py-1 text-[11px] ${index === 0 ? 'bg-emerald-700 font-semibold text-white' : 'bg-[#f0f6fb] text-[#32415d]'}`}>{tag}</span>)}</div><dl className="mt-3 grid grid-cols-1 gap-x-4 sm:grid-cols-2">{details.map(([label, value]) => <div key={label} className="flex min-h-10 items-center justify-between gap-2 border-t border-[#ebeff1] text-[11px]"><dt className="text-slate-500">{label}</dt><dd className="text-right font-semibold text-[#17233c]">{value}</dd></div>)}</dl></div></section>
}

export function PassportQRCard({ product }) {
  return <section id="passport-qr" className={card}><div className="flex items-start gap-2"><a href="#product-journey" aria-label={`View the journey for ${product.name}`} className="shrink-0"><img src="/images/consumer/farm-passport-qr.png" alt={`Farm passport QR code for ${product.name}`} className="size-[94px] bg-white object-contain sm:size-[104px]" /></a><div><h2 className="text-sm font-bold text-[#172033]">Scan to Verify</h2><p className="mt-2 text-xs leading-[1.45] text-slate-600">Scan this QR code to view this product’s complete journey, certificates and real-time information.</p></div></div><div className="mt-3 flex items-center gap-2 rounded-lg bg-gradient-to-r from-[#e8f9ee] to-[#f3fff7] px-2 py-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-emerald-700 text-white"><Check size={17} /></span><span><strong className="block text-xs text-[#075b32]">Verified by KhetSetu AI</strong><small className="text-[10px] text-slate-600">Authentic farm product • Tamper-proof data</small></span></div></section>
}

const featureIcons = [QrCode, PackageCheck, MapPin, Sprout, ShieldCheck, BadgeCheck]
export function PassportFeatures({ features }) {
  return <section className={`${card} h-fit bg-gradient-to-br from-white to-[#f1fff5] xl:col-start-3 xl:row-span-2`}><SectionHeading icon={Award}>Key Features</SectionHeading><div className="divide-y divide-[#e7eee9]">{features.map((feature, index) => { const Icon = featureIcons[index]; return <a key={feature.title} href={`#${feature.anchor}`} className="flex min-h-[59px] items-center gap-2 py-1.5 hover:bg-emerald-50"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[#dff9e9] text-emerald-800"><Icon size={20} /></span><span className="min-w-0 flex-1"><strong className="block text-[12px] text-[#17233c]">{feature.title}</strong><small className="block text-[10px] leading-4 text-slate-500">{feature.detail}</small></span><ChevronRight size={16} className="text-emerald-800" /></a> })}</div></section>
}

const gallery = [
  { src: '/images/dashboard/healthy-crops.png', alt: 'Rice plants growing in a field', position: 'center 68%' },
  { src: '/images/dashboard/farmer-hero.png', alt: 'Sundar Farms fields', position: 'left 75%' },
  { src: '/images/consumer/promo.png', alt: 'A thriving farm landscape', position: 'center' },
  { src: '/images/dashboard/farmer-hero.png', alt: 'Fields and hills around the farm', position: '28% 75%' },
]
export function FarmerInformation({ farm }) {
  return <section id="farm-story" className={card}><SectionHeading icon={UsersRound}>Farm &amp; Farmer Information</SectionHeading><div className="grid gap-3 sm:grid-cols-[minmax(125px,.75fr)_minmax(160px,1fr)] lg:grid-cols-[minmax(125px,.85fr)_minmax(160px,1fr)_minmax(160px,1fr)]"><img src="/images/dashboard/farmer-hero.png" alt={`${farm.farmer} of ${farm.name}`} className="h-[175px] w-full rounded-lg object-cover object-[85%_center]" /><div className="text-xs"><h3 className="text-[15px] font-bold text-[#172033]">{farm.name}</h3><span className="mt-1 inline-flex items-center gap-1 rounded-full bg-[#dcf9e7] px-2 py-1 font-semibold text-emerald-900"><ShieldCheck size={14} fill="currentColor" />Verified Farm</span><p className="mt-2 flex items-start gap-2 text-[#354461]"><MapPin size={15} className="shrink-0" />{farm.location}</p><p className="mt-2 flex items-start gap-2 text-[#354461]"><UsersRound size={15} className="shrink-0" /><span>{farm.farmer}<span className="block text-slate-500">{farm.generation}</span></span></p><p className="mt-2 flex items-center gap-2 text-[#354461]"><CalendarDays size={15} />Farming Since {farm.since}</p><p className="mt-2 flex items-center gap-2 text-[#354461]"><House size={15} />Farm Size {farm.size}</p></div><blockquote className="rounded-lg bg-gradient-to-br from-[#f0fbf4] to-white px-3 py-2 text-[12px] leading-[1.4] text-[#34415e] sm:col-span-2 lg:col-span-1"><span className="text-2xl font-bold leading-3 text-emerald-700">“</span>{farm.quote}”<footer className="mt-2 pl-3 text-[11px] font-semibold text-[#17233c]">— {farm.farmer}<span className="block pl-4 font-normal text-slate-500">{farm.name}</span></footer></blockquote></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{gallery.map(image => <img key={image.alt} src={image.src} alt={image.alt} style={{ objectPosition: image.position }} className="h-[88px] w-full rounded-lg object-cover" />)}</div></section>
}

function FarmMap({ farm }) {
  return <div role="img" aria-label={`Illustrated map showing ${farm.name} near Sitapur, Uttar Pradesh`} className="relative h-[215px] overflow-hidden rounded-lg bg-[#f6f7eb]"><svg viewBox="0 0 340 215" preserveAspectRatio="xMidYMid slice" className="absolute inset-0 size-full"><rect width="340" height="215" fill="#f7f7ed" /><path d="M0 40 C70 10 110 50 155 18 S265 28 340 0 L340 105 C255 145 130 115 0 145Z" fill="#ecf4df" /><path d="M0 183 C50 168 78 185 120 155 S205 165 260 148 S305 125 340 135" fill="none" stroke="#c5dfeb" strokeWidth="15" opacity=".65" /><path d="M0 185 C50 168 78 185 120 155 S205 165 260 148 S305 125 340 135" fill="none" stroke="#9ed0e6" strokeWidth="3" /><path d="M-10 48 C45 70 80 95 138 82 S265 90 350 60 M28 230 C50 160 130 142 178 108 S225 25 292 -10 M-10 138 C70 130 120 140 190 72 S273 67 350 30" fill="none" stroke="#f0c576" strokeWidth="4" /><path d="M-10 48 C45 70 80 95 138 82 S265 90 350 60 M28 230 C50 160 130 142 178 108 S225 25 292 -10 M-10 138 C70 130 120 140 190 72 S273 67 350 30" fill="none" stroke="white" strokeWidth="2" /><path d="M0 24 C78 58 104 25 150 55 S252 40 340 75 M0 115 C65 96 100 130 160 125 S280 167 340 190" fill="none" stroke="#d6dfd1" strokeWidth="1.4" strokeDasharray="3 3" /><text x="225" y="63" fontSize="12" fill="#344351">Sitapur</text><text x="244" y="186" fontSize="12" fill="#344351">Lucknow</text></svg><div className="absolute left-[28%] top-[44%] flex items-center gap-1 rounded-md bg-white/95 px-2 py-1 text-[10px] shadow"><MapPin className="size-6 fill-emerald-700 text-emerald-700" /><span><strong className="block text-[#143c2c]">{farm.name}</strong>{farm.location}</span></div></div>
}
export function FarmLocation({ farm }) {
  const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(farm.address + ', ' + farm.fullAddress)}`
  return <section id="farm-location" className={card}><SectionHeading icon={MapPin} action={<a href={mapUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-[11px] text-emerald-900 hover:underline">View on Map <ArrowRight size={15} /></a>}>Farm Location</SectionHeading><FarmMap farm={farm} /><a href={mapUrl} target="_blank" rel="noreferrer" className="mt-2 flex items-center gap-2 rounded-lg border border-[#e5edf0] bg-[#f8fbfd] p-2 text-[11px] text-[#34415e] hover:bg-emerald-50"><MapPin className="size-5 shrink-0 text-slate-500" /><span className="flex-1"><strong className="block font-medium">{farm.address}</strong>{farm.fullAddress}</span><ExternalLink className="size-4 shrink-0 text-emerald-800" /></a></section>
}

const journeyIcons = [Sprout, CalendarDays, ShieldCheck, PackageCheck, Truck, House]
export function ProductJourney({ journey }) {
  return <section id="product-journey" className={card}><SectionHeading icon={Truck}>Product Journey</SectionHeading><p className="-mt-2 mb-5 pl-8 text-xs text-slate-500">From farm to your home — complete transparency at every step.</p><ol className="relative grid gap-4 pl-2 sm:grid-cols-3 sm:gap-2 sm:pl-0 xl:grid-cols-6"><span aria-hidden="true" className="absolute bottom-10 left-[25px] top-7 w-0.5 bg-emerald-700 sm:bottom-auto sm:left-[8%] sm:right-[8%] sm:top-[26px] sm:h-0.5 sm:w-auto" />{journey.map((step, index) => { const Icon = journeyIcons[index]; return <li key={step.title} className="relative flex items-center gap-3 sm:block sm:text-center"><div className="relative z-10 grid size-[52px] shrink-0 place-items-center rounded-full border border-emerald-100 bg-[#e7fff0] text-emerald-800 sm:mx-auto"><Icon size={25} fill={index === 5 ? 'currentColor' : 'none'} /><span className="absolute -top-2 left-1/2 grid size-5 -translate-x-1/2 place-items-center rounded-full border-2 border-white bg-[#38a33a] text-white"><Check size={12} /></span></div><div className="sm:mt-2"><h3 className="text-[11px] font-bold text-[#14233a]">{index + 1}. {step.title}</h3><p className="mt-1 text-[11px] text-slate-500">{step.date}</p><p className="mt-1 text-[11px] leading-4 text-slate-600">{step.detail}</p></div></li> })}</ol></section>
}

export function QualityLabStatus({ quality, onViewReport }) {
  return <section id="quality-status" className={card}><SectionHeading icon={FlaskConical} action={<button type="button" onClick={onViewReport} className="inline-flex items-center gap-1 text-[11px] text-emerald-900 hover:underline">View Report <ArrowRight size={15} /></button>}>Quality &amp; Lab Status</SectionHeading><div className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-[#dff8e6] to-[#f1fff5] px-3 py-2"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-emerald-700 text-white"><Check size={20} /></span><span><strong className="block text-xs text-[#075b32]">Passed All Quality Checks</strong><small className="text-[10px] text-slate-600">Tested at NABL accredited laboratory</small></span></div><dl className="mt-1 divide-y divide-[#e7edf0] rounded-lg border border-[#e7edf0] px-2">{quality.map(check => <div key={check.name} className="flex min-h-[25px] items-center justify-between gap-2 text-[11px]"><dt className="text-slate-600">{check.name}</dt><dd className="text-right font-semibold text-emerald-800">{check.result}</dd></div>)}</dl><button type="button" onClick={onViewReport} className="mt-2 flex w-full items-center justify-between rounded-lg border border-[#dcece7] px-3 py-2 text-xs text-[#28344c] hover:bg-emerald-50"><span className="flex items-center gap-2"><ClipboardCheck size={19} className="text-emerald-800" />View Detailed Lab Report</span><ChevronRight size={16} className="text-emerald-800" /></button></section>
}

function CertificationMark({ mark }) {
  if (mark === 'fssai') return <span aria-hidden="true" className="text-[19px] font-bold italic leading-none tracking-tight text-[#273778]">fssai</span>
  if (mark === 'quality') return <Award size={28} className="text-amber-500" />
  return <Leaf size={29} className="fill-emerald-700 text-emerald-700" />
}
export function CertificationsTrust({ certifications }) {
  return <section id="certifications" className={card}><SectionHeading icon={ShieldCheck}>Certifications &amp; Trust</SectionHeading><div className="divide-y divide-[#e8eef0] border-t border-[#e8eef0]">{certifications.map(item => <div key={item.title} className="flex min-h-[54px] items-center gap-2"><span className="grid w-10 shrink-0 place-items-center"><CertificationMark mark={item.mark} /></span><span className="min-w-0 flex-1"><strong className="block truncate text-[11px] text-[#17233c]">{item.title}</strong><small className="block truncate text-[10px] text-slate-500">{item.detail}</small></span><span className="inline-flex items-center gap-1 rounded-full bg-[#e1f9e9] px-1.5 py-1 text-[10px] font-semibold text-emerald-800"><BadgeCheck size={11} fill="currentColor" />Verified</span></div>)}</div></section>
}

export function LabReportDialog({ product, quality, onClose }) {
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/45 p-4" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><div role="dialog" aria-modal="true" aria-labelledby="lab-report-title" className="w-full max-w-md rounded-xl bg-white p-5 shadow-xl"><div className="flex items-start justify-between gap-3"><div><h2 id="lab-report-title" className="text-lg font-bold text-[#17233c]">Quality &amp; Lab Report</h2><p className="mt-1 text-xs text-slate-500">{product.name} · Batch {product.batchId}</p></div><button type="button" onClick={onClose} aria-label="Close lab report" className="rounded p-1 hover:bg-slate-100"><X size={19} /></button></div><p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">Passed All Quality Checks</p><dl className="mt-3 divide-y divide-slate-100">{quality.map(item => <div key={item.name} className="flex justify-between gap-3 py-2 text-sm"><dt className="text-slate-600">{item.name}</dt><dd className="font-medium text-emerald-800">{item.result}</dd></div>)}</dl><p className="mt-3 text-xs text-slate-500">Prototype record. The full laboratory certificate will be available when verified documents are connected.</p></div></div>
}
