import { useState } from 'react'
import { BadgeIndianRupee, Banknote, BarChart3, Box, CalendarDays, CheckCircle2, ChevronDown, CircleDollarSign, Clock3, CreditCard, FileText, Gift, Info, Leaf, MapPin, Target, UserRound, WalletCards, X, XCircle, Star } from 'lucide-react'
import earningsReference from '../../../../Images/delevery/ChatGPT Image Sep 23, 2026, 09_54_23 PM (4).png'
import { earningsBreakdown, earningsFeatures, earningsSummary, earningsTrend, performanceMetrics, weeklyDeliveries } from '../data/earnings.mock'
import '../earnings.css'

const iconSets={rupee:BadgeIndianRupee,calendar:CalendarDays,chart:BarChart3,gift:Gift,user:UserRound,pin:MapPin,penalty:XCircle,check:CheckCircle2,clock:Clock3,star:Star,box:Box,target:Target,report:FileText,wallet:WalletCards,card:CreditCard}

function EarningsHero(){return <section className="earnings-hero" style={{'--earnings-art':`url("${earningsReference}")`}}><div className="earnings-hero-copy"><h1>Earnings &amp; Incentives <Leaf/></h1><p>Your effort delivers more than food. It builds a healthier tomorrow.</p></div><div className="earnings-hero-script">Good<br/><span>Food Reaches</span><br/>Further</div><div className="earnings-hero-brand"><Leaf/><strong>Fresh Farms<br/>Stronger Cities</strong></div></section>}

function SummaryCards(){return <section className="earnings-summary" aria-label="Earnings summary">{earningsSummary.map(item=>{const Icon=iconSets[item.icon];return <article key={item.label}><span><Icon/></span><div><p>{item.label}</p><div><strong>{item.value}</strong><em>↗ {item.trend}</em></div><small>{item.detail}</small></div></article>})}</section>}

function EarningsPanelHeader({icon:Icon,title,subtitle,action}){return <header className="earnings-panel-header"><div><Icon/><span><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</span></div>{action}</header>}

function RangeSelect({value,onChange,children}){return <label className="earnings-range"><span className="sr-only">Chart range</span><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select><ChevronDown/></label>}

function EarningsTrendChart(){
  const [range,setRange]=useState('Last 30 Days')
  const min=0,max=2500
  const points=earningsTrend.map((value,index)=>({x:index/(earningsTrend.length-1)*100,y:(value-min)/(max-min)*100,value}))
  const polygon=`0% 100%, ${points.map(point=>`${point.x}% ${100-point.y}%`).join(', ')}, 100% 100%`
  return <section className="earnings-chart-panel trend-chart-panel"><EarningsPanelHeader icon={BarChart3} title="Earnings Trend" subtitle="Track your earnings over time" action={<RangeSelect value={range} onChange={setRange}><option>Last 30 Days</option><option>Last 3 Months</option><option>This Year</option></RangeSelect>}/><div className="trend-chart"><div className="trend-y-axis">{['₹ 2,500','₹ 2,000','₹ 1,500','₹ 1,000','₹ 500','₹ 0'].map(label=><span key={label}>{label}</span>)}</div><div className="trend-plot"><div className="trend-area" style={{clipPath:`polygon(${polygon})`}}/>{points.slice(0,-1).map((point,index)=>{const next=points[index+1];const dx=next.x-point.x;const dy=(100-next.y)-(100-point.y);const width=Math.sqrt(dx*dx+dy*dy);const angle=Math.atan2(dy,dx)*180/Math.PI;return <i className="trend-segment" key={index} style={{left:`${point.x}%`,top:`${100-point.y}%`,width:`${width}%`,transform:`rotate(${angle}deg)`}}/>})}{points.map((point,index)=><b key={index} className={`trend-point ${index===18?'featured':''}`} style={{left:`${point.x}%`,top:`${100-point.y}%`}}>{index===18&&<span>Apr 17, 2025<strong>₹ 1,820</strong></span>}</b>)}</div><div className="trend-x-axis">{['Mar 30','Apr 2','Apr 5','Apr 8','Apr 11','Apr 14','Apr 17','Apr 20','Apr 23','Apr 26','Apr 28'].map(label=><span key={label}>{label}</span>)}</div></div></section>
}

function DeliveriesBarChart(){const [range,setRange]=useState('Last 4 Weeks');return <section className="earnings-chart-panel deliveries-chart-panel"><EarningsPanelHeader icon={BarChart3} title="Deliveries Completed" subtitle="Weekly delivery count" action={<RangeSelect value={range} onChange={setRange}><option>Last 4 Weeks</option><option>Last 8 Weeks</option><option>Last 12 Weeks</option></RangeSelect>}/><div className="bars-chart"><div className="bars-y-axis">{[100,80,60,40,20,0].map(value=><span key={value}>{value}</span>)}</div><div className="bars-plot">{weeklyDeliveries.map(item=><div className="bar-column" key={item.label}><div className="bar-value">{item.value}</div><i style={{height:`${item.value}%`}}/><span>{item.label}</span></div>)}</div></div></section>}

function EarningsBreakdown(){return <section className="earnings-lower-panel breakdown-panel"><EarningsPanelHeader icon={CircleDollarSign} title="Earnings Breakdown" subtitle="Detailed view of your earnings"/><div className="breakdown-rows">{earningsBreakdown.map(item=>{const Icon=iconSets[item.icon];return <article className={item.negative?'negative':''} key={item.title}><span><Icon/></span><div><strong>{item.title}</strong><small>{item.detail}</small></div><b>{item.amount}</b><em>{item.percent}</em></article>})}</div><div className="earnings-total"><div><strong>Total Earnings</strong><small>For Apr 1 - Apr 28, 2025</small></div><b>₹ 28,460</b><em>100%</em></div></section>}

function PayoutPanel(){const [modal,setModal]=useState(false);return <section className="earnings-lower-panel payout-panel"><EarningsPanelHeader icon={WalletCards} title="Payout & Withdrawal" subtitle="Get paid for your hard work"/><div className="upcoming-payout"><span><CalendarDays/></span><div><small>Upcoming Payout</small><strong>May 2, 2025 <em>(in 4 days)</em></strong></div></div><div className="bank-row"><Banknote/><div><small>Bank Account (UPI)</small><strong>•••• 9876</strong></div><span>Verified <CheckCircle2/></span></div><div className="payout-info"><Info/><p>Payouts are processed every Friday.<br/>Earnings will be credited to your registered<br/>bank account or UPI ID.</p></div><button className="early-payout" type="button" onClick={()=>setModal(true)}><BadgeIndianRupee/>Request Early Payout</button>{modal&&<div className="payout-modal" role="dialog" aria-modal="true" aria-label="Request early payout"><div><button type="button" onClick={()=>setModal(false)} aria-label="Close"><X/></button><WalletCards/><h3>Request early payout?</h3><p>₹28,460 will be sent to your verified UPI account ending in 9876.</p><button type="button" onClick={()=>setModal(false)}>Confirm Request</button></div></div>}</section>}

function PerformancePanel(){return <section className="earnings-lower-panel performance-panel"><EarningsPanelHeader icon={Target} title="Delivery Performance" subtitle="Your performance drives your earnings"/><div>{performanceMetrics.map(item=>{const Icon=iconSets[item.icon];return <article key={item.label}><span><Icon/></span><div><small>{item.label}</small><strong>{item.value}</strong><p>{item.detail}</p></div><em>↗ {item.trend}</em></article>})}</div></section>}

function EarningsFeatures(){return <section className="earnings-lower-panel earnings-features"><EarningsPanelHeader icon={Leaf} title="Key Features" subtitle="Everything you need, in one place"/><div>{earningsFeatures.map(item=>{const Icon=iconSets[item.icon];return <article key={item.label}><Icon/><span>{item.label}</span></article>})}</div></section>}

export default function DeliveryEarnings(){return <><EarningsHero/><div className="earnings-page-content"><SummaryCards/><div className="earnings-charts-grid"><EarningsTrendChart/><DeliveriesBarChart/></div><div className="earnings-lower-grid"><EarningsBreakdown/><PayoutPanel/><div className="earnings-right-stack"><PerformancePanel/><EarningsFeatures/></div></div></div></>}
