import { useMemo, useState } from 'react'
import { BarChart3, Box, CalendarDays, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Clock3, Download, FileText, Filter, History, Image, Leaf, MapPin, Maximize2, MessageCircle, Package, Phone, Star, Timer, UserRound, X, XCircle } from 'lucide-react'
import { historyDeliveries, historyFeatures, historySummary } from '../data/history.mock'
import '../history.css'

const summaryIcons={box:Box,check:CheckCircle2,failed:XCircle,star:Star}
const featureIcons={record:FileText,feedback:MessageCircle,photo:Image,star:Star,history:History,chart:BarChart3}

function HistoryHeader({onExport}){return <section className="history-header"><div><h1>Delivery History <Leaf/></h1><p>Track your past deliveries, view details and your performance.</p></div><button type="button" onClick={onExport}><Download/>Export History</button></section>}

function HistorySummary(){return <section className="history-summary" aria-label="Delivery history summary">{historySummary.map(item=>{const Icon=summaryIcons[item.icon];return <article key={item.label}><span className={item.tone}><Icon/></span><div><p>{item.label}</p><div><strong>{item.value}</strong><em className={item.tone==='red'?'negative':''}>{item.tone==='red'?'↓':'↗'} {item.trend}</em></div><small>{item.detail}</small></div></article>})}</section>}

function HistoryFilters({draft,setDraft,apply,clear}){const update=(key,value)=>setDraft(current=>({...current,[key]:value}));return <section className="history-filters"><label><CalendarDays/><span><small>Date Range</small><select value={draft.date} onChange={e=>update('date',e.target.value)}><option>Apr 1, 2025 - Apr 30, 2025</option><option>Mar 1, 2025 - Mar 31, 2025</option></select></span><ChevronDown/></label><label><Filter/><span><small>Status</small><select value={draft.status} onChange={e=>update('status',e.target.value)}><option>All Deliveries</option><option>Delivered</option><option>Failed</option></select></span><ChevronDown/></label><label><MapPin/><span><small>Location</small><select value={draft.location} onChange={e=>update('location',e.target.value)}><option>All Areas</option><option>Lanka</option><option>Sigra</option><option>Assi Ghat</option><option>Cantonment</option><option>BHU</option><option>Varanasi Cantt</option></select></span><ChevronDown/></label><div className="history-filter-actions"><button type="button" onClick={clear}>Clear Filters</button><button type="button" onClick={apply}><Filter/>Apply Filters</button></div></section>}

function HistoryStatus({status}){return <span className={`history-status ${status.toLowerCase()}`}>{status}</span>}

function MobileHistoryCard({item,selected,onSelect}){return <button type="button" className={`mobile-history-card ${selected?'selected':''}`} onClick={onSelect}><div><strong>{item.id}</strong><HistoryStatus status={item.status}/></div><section><span>{item.emoji}</span><div><h3>{item.product}</h3><p>{item.customer} • {item.weight}</p></div><b>{item.earnings}</b></section><footer><span>{item.area}</span><time>{item.date} • {item.time}</time></footer></button>}

function HistoryTable({items,selected,onSelect,sort,setSort}){return <section className="history-table-panel"><header><h2>Delivery History (248)</h2><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option>Newest First</option><option>Oldest First</option><option>Highest Earnings</option><option>Best Rating</option></select><ChevronDown/></label></header><div className="history-table-wrap"><table><thead><tr><th>Order ID</th><th>Customer</th><th>Product</th><th>Area</th><th>Date &amp; Time</th><th>Status</th><th>Earnings</th><th>Rating</th><th/></tr></thead><tbody>{items.map(item=><tr key={item.id} onClick={()=>onSelect(item)} className={selected?.id===item.id?'selected':''}><td>{item.id}</td><td><span className="history-customer"><UserRound/>{item.customer}</span></td><td><span className="history-product"><i>{item.emoji}</i><span>{item.product}<small>{item.weight}</small></span></span></td><td>{item.area}</td><td>{item.date}<small className="history-time">{item.time}</small></td><td><HistoryStatus status={item.status}/></td><td><strong>{item.earnings}</strong></td><td>{item.rating!=='-'?<span className="history-rating"><Star/>{item.rating}</span>:'-'}</td><td><ChevronRight/></td></tr>)}</tbody></table><div className="history-mobile-list">{items.map(item=><MobileHistoryCard key={item.id} item={item} selected={selected?.id===item.id} onSelect={()=>onSelect(item)}/>)}</div>{items.length===0&&<div className="history-empty"><Package/><strong>No delivery records found</strong><span>Try changing your filters.</span></div>}</div><footer><p>Showing 1–{items.length} of 248 deliveries</p><nav aria-label="History pagination"><button disabled aria-label="Previous page"><ChevronLeft/></button>{[1,2,3,4,5].map(page=><button key={page} className={page===1?'active':''}>{page}</button>)}<span>…</span><button>31</button><button aria-label="Next page"><ChevronRight/></button></nav></footer></section>}

function HistoryDetails({item,onClose,onPreview}){if(!item)return <aside className="history-details empty"><Package/><h2>Select a delivery</h2><p>Choose a history record to view its details.</p></aside>;const delivered=item.status==='Delivered';return <aside className="history-details"><header><h2><Box/>Delivery Details</h2><div><HistoryStatus status={item.status}/><button type="button" onClick={onClose} aria-label="Close details"><X/></button></div></header><div className="history-details-body"><section className="history-order"><div><small>Order ID</small><strong>{item.id}</strong></div><time>{item.date}<strong>{item.time}</strong></time></section><section className="history-customer-detail"><UserRound/><span><small>Customer</small><strong>Mr. {item.customer}</strong><em>Store Manager</em><p><Phone/>{item.phone}</p></span><button type="button" aria-label="Call customer"><Phone/></button></section><section className="history-product-detail"><MapPin/><span className="product-picture">{item.emoji}</span><div><strong>{item.product}</strong><p><em>{item.category}</em><small>{item.weight}</small></p></div><b>{item.earnings}</b></section><section className="history-area-detail"><MapPin/><div><small>Delivery Area</small><strong>{item.area}</strong><p>{item.address}</p></div></section>{delivered&&<><section className="proof-section"><h3><BarChart3/>Proof of Delivery</h3><div><button type="button" className="proof-picture" onClick={onPreview}><span>📦 🍅🍅🍅</span><Maximize2/></button><div className="otp-proof"><CheckCircle2/><span><strong>OTP Verified</strong><small>OTP: 472910</small><small>Verified at 10:31 AM</small></span></div></div></section><section className="drop-notes"><FileText/><strong>Drop-off Notes</strong><p>Handed over to store manager at main gate.<br/>All items received in good condition.</p></section><section className="customer-feedback"><MessageCircle/><strong>Customer Feedback</strong><div><span>★★★★★</span><b>{item.rating}</b><p>“Very fresh vegetables and on-time delivery.<br/>Great service!”</p></div></section></>}</div></aside>}

function PerformanceInsights(){const [range,setRange]=useState('Last 30 Days');return <section className="history-bottom-panel performance-insights"><header><h2><BarChart3/>Performance Insights</h2><label><select value={range} onChange={e=>setRange(e.target.value)}><option>Last 30 Days</option><option>Last 90 Days</option><option>This Year</option></select><ChevronDown/></label></header><div><article><span className="green"><Clock3/></span><div><small>On-Time Rate</small><strong>96.2%</strong><p>vs. previous month</p></div><em>↗ +4%</em></article><article><span className="blue"><Timer/></span><div><small>Average Delivery Time</small><strong>28 mins</strong><p>from pickup to drop</p></div><em className="down">↓ -12%</em></article><article><span className="purple"><MapPin/></span><div><small>Most Frequent Area</small><strong>Lanka</strong><p>42 deliveries</p></div></article></div></section>}

function HistoryFeatures(){return <section className="history-bottom-panel history-features"><header><h2><Star/>Key Features</h2></header><div>{historyFeatures.map(feature=>{const Icon=featureIcons[feature.icon];return <article key={feature.title}><span><Icon/></span><div><strong>{feature.title}</strong><small>{feature.detail}</small></div></article>})}</div></section>}

export default function DeliveryHistory(){
  const defaults={date:'Apr 1, 2025 - Apr 30, 2025',status:'All Deliveries',location:'All Areas'}
  const [draft,setDraft]=useState(defaults),[filters,setFilters]=useState(defaults),[sort,setSort]=useState('Newest First'),[selected,setSelected]=useState(historyDeliveries[0]),[preview,setPreview]=useState(false)
  const items=useMemo(()=>{let result=historyDeliveries.filter(item=>filters.date.startsWith('Apr')&&(filters.status==='All Deliveries'||item.status===filters.status)&&(filters.location==='All Areas'||item.area===filters.location));if(sort==='Oldest First')result=[...result].reverse();if(sort==='Highest Earnings')result=[...result].sort((a,b)=>Number(b.earnings.replace(/\D/g,''))-Number(a.earnings.replace(/\D/g,'')));if(sort==='Best Rating')result=[...result].sort((a,b)=>(Number(b.rating)||0)-(Number(a.rating)||0));return result},[filters,sort])
  const exportHistory=()=>{const rows=[['Order ID','Customer','Product','Area','Date','Status','Earnings'],...historyDeliveries.map(item=>[item.id,item.customer,item.product,item.area,`${item.date} ${item.time}`,item.status,item.earnings])];const blob=new Blob([rows.map(row=>row.join(',')).join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='khetsetu-delivery-history.csv';link.click();URL.revokeObjectURL(url)}
  const clear=()=>{setDraft(defaults);setFilters(defaults)}
  return <><HistoryHeader onExport={exportHistory}/><div className="history-page-content"><HistorySummary/><HistoryFilters draft={draft} setDraft={setDraft} apply={()=>setFilters(draft)} clear={clear}/><div className="history-workspace"><HistoryTable items={items} selected={selected} onSelect={setSelected} sort={sort} setSort={setSort}/><HistoryDetails item={selected} onClose={()=>setSelected(null)} onPreview={()=>setPreview(true)}/></div><div className="history-bottom-grid"><PerformanceInsights/><HistoryFeatures/></div></div>{preview&&<div className="proof-preview" role="dialog" aria-modal="true" aria-label="Proof of delivery preview"><div><button type="button" onClick={()=>setPreview(false)}><X/></button><span>📦</span><p>Fresh Tomatoes delivered successfully</p></div></div>}</>
}
