import { useMemo, useState } from 'react'
import { AlertTriangle, Box, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ClipboardList, Filter, Leaf, MapPin, MessageSquare, Navigation, Package, Phone, RefreshCw, Search, Settings, Truck, UserRound, X } from 'lucide-react'
import deliveriesReference from '../../../../Images/delevery/ChatGPT Image Sep 23, 2026, 09_54_21 PM (2).png'
import { deliveries, deliveryFeatures, deliveryStats } from '../data/deliveries.mock'
import '../my-deliveries.css'

const statIcons = { package:Box, truck:Truck, check:CheckCircle2, alert:AlertTriangle }
const featureIcons = { list:ClipboardList, filter:Filter, phone:Phone, pin:MapPin, alert:AlertTriangle, settings:Settings }
const statusClass = status => status.toLowerCase().replaceAll(' ', '-')

function DeliveriesHero() {
  return <section className="deliveries-hero" style={{ '--deliveries-art':`url("${deliveriesReference}")` }}><div className="deliveries-hero-copy"><h1>My Deliveries <Leaf /></h1><p>Manage your deliveries, keep farmers and families connected.</p></div><div className="deliveries-hero-script">Good<br /><span>Food Reaches</span><br />Further</div><div className="deliveries-hero-brand"><Leaf /><strong>Fresh Farms<br />Stronger Cities</strong></div></section>
}

function DeliveryStats() {
  return <section className="deliveries-stats" aria-label="Delivery statistics">{deliveryStats.map(stat => { const Icon=statIcons[stat.icon]; return <article key={stat.label} className="deliveries-stat"><span className={`deliveries-stat-icon ${stat.tone}`}><Icon /></span><div><p>{stat.label}</p><div><strong>{stat.value}</strong><em className={stat.tone === 'red' ? 'negative' : ''}>{stat.tone === 'red' ? '↓' : '↗'} {stat.trend}</em></div><small>{stat.detail}</small></div></article> })}</section>
}

function Filters({ filters, setFilters, reset }) {
  const update = (key, value) => setFilters(current => ({ ...current, [key]:value }))
  return <section className="deliveries-filters"><label className="deliveries-filter-search"><Search /><span className="sr-only">Search deliveries</span><input value={filters.search} onChange={e => update('search',e.target.value)} placeholder="Search by Order ID, customer name, or product..." /></label><label><span className="sr-only">Filter by status</span><select value={filters.status} onChange={e => update('status',e.target.value)}><option>All Status</option><option>Assigned</option><option>In Transit</option><option>Picked Up</option><option>Delivered</option><option>Delayed</option></select><ChevronDown /></label><label className="date-filter"><CalendarDays /><span className="sr-only">Filter by date</span><select value={filters.date} onChange={e => update('date',e.target.value)}><option value="today">Today, Apr 28, 2025</option><option value="tomorrow">Tomorrow, Apr 29, 2025</option></select><ChevronDown /></label><label><MapPin /><span className="sr-only">Filter by area</span><select value={filters.area} onChange={e => update('area',e.target.value)}><option>All Areas</option><option>Lanka</option><option>Sigra</option><option>Bhelupur</option><option>Assi</option><option>Cantt</option></select><ChevronDown /></label><button type="button" className="deliveries-reset" onClick={reset}><RefreshCw />Reset</button></section>
}

function StatusBadge({ status }) { return <span className={`delivery-status ${statusClass(status)}`}>{status}</span> }

function MobileDeliveryCard({ delivery, selected, onSelect }) {
  return <button type="button" className={`mobile-delivery-card ${selected ? 'selected' : ''}`} onClick={onSelect}><div><strong>{delivery.id}</strong><StatusBadge status={delivery.status} /></div><h3>{delivery.customer}</h3><p>{delivery.product} • {delivery.weight}</p><small>{delivery.pickup} <ChevronRight /> {delivery.drop}</small><time>{delivery.time}</time></button>
}

function DeliveriesList({ items, selectedId, onSelect, page, setPage, total }) {
  return <section className="deliveries-list-panel"><header><h2><span><Check /></span>Deliveries ({total})</h2><button type="button">Sort by: <strong>Pickup Time</strong><ChevronRight /></button></header><div className="deliveries-table-wrap"><table><thead><tr><th><span className="fake-check" /></th><th>Order ID</th><th>Customer</th><th>Product</th><th>Pickup <ChevronRight /> Drop</th><th>Time Slot</th><th>Weight</th><th>Status</th><th /></tr></thead><tbody>{items.map(delivery => <tr key={delivery.id} className={selectedId === delivery.id ? 'selected' : ''} onClick={() => onSelect(delivery)}><td><span className={`fake-check ${selectedId === delivery.id ? 'checked' : ''}`}>{selectedId === delivery.id && <Check />}</span></td><td>{delivery.id}</td><td>{delivery.customer}</td><td>{delivery.product}</td><td><span className="route-cell">{delivery.pickup}<small><ChevronRight /> {delivery.drop}</small></span></td><td>{delivery.time}</td><td>{delivery.weight}</td><td><StatusBadge status={delivery.status} /></td><td><ChevronRight /></td></tr>)}</tbody></table><div className="deliveries-mobile-list">{items.map(delivery => <MobileDeliveryCard key={delivery.id} delivery={delivery} selected={selectedId === delivery.id} onSelect={() => onSelect(delivery)} />)}</div>{items.length === 0 && <div className="deliveries-empty"><Package /><strong>No deliveries found</strong><span>Try changing your search or filters.</span></div>}</div><footer><p>Showing {items.length ? (page-1)*8+1 : 0}–{Math.min(page*8,total)} of {total} deliveries</p><nav aria-label="Delivery list pagination"><button type="button" disabled={page===1} onClick={() => setPage(page-1)} aria-label="Previous page"><ChevronLeft /></button><button type="button" className={page===1?'active':''} onClick={() => setPage(1)}>1</button><button type="button" className={page===2?'active':''} onClick={() => setPage(2)}>2</button><button type="button" disabled={page===2 || total<=8} onClick={() => setPage(page+1)} aria-label="Next page"><ChevronRight /></button></nav></footer></section>
}

function DeliveryDetails({ delivery, onClose }) {
  const [menuOpen,setMenuOpen] = useState(false)
  const [issueOpen,setIssueOpen] = useState(false)
  if (!delivery) return <aside className="delivery-details empty-detail"><Package /><h2>Select a delivery</h2><p>Choose a delivery to view its complete details.</p></aside>
  return <aside className="delivery-details"><header><h2><Box />Delivery Details</h2><div><span className="details-way">On the way</span><button type="button" onClick={onClose} aria-label="Close delivery details"><X /></button></div></header><div className="details-body"><section className="details-summary"><div><small>Order ID</small><strong>{delivery.id}</strong></div><div><small>Current Status</small><StatusBadge status={delivery.status} /></div></section><section className="details-customer"><UserRound /><div><small>Customer</small><strong>Mr. {delivery.customer}</strong><p>{delivery.phone}</p></div><span><CheckCircle2 />Verified</span><button type="button" aria-label="Call customer"><Phone /></button><button type="button" aria-label="Message customer"><MessageSquare /></button></section><section className="details-product"><Box /><span className="details-product-emoji">{delivery.emoji}</span><div><small>Product Details</small><strong>{delivery.product} ({delivery.batch})</strong><p><em>{delivery.category}</em><b>{delivery.weight}</b></p></div></section><section className="location-detail"><MapPin /><div><small>Pickup Location</small><strong>{delivery.pickup}</strong><p>{delivery.pickupDetail}</p></div><span><small>Picked Up</small><strong>{delivery.pickupTime}</strong></span></section><section className="location-detail drop"><MapPin /><div><small>Drop Location</small><strong>{delivery.drop}, Varanasi</strong><p>{delivery.dropDetail}</p></div><span><small>Expected</small><strong>{delivery.expectedTime}</strong></span></section><section className="instructions-detail"><ClipboardList /><div><strong>Delivery Instructions</strong><p>Call customer 10 minutes before arrival.<br />Leave at doorstep if unavailable.<br />Handle with care - fresh produce.</p></div></section></div><div className="details-actions"><button type="button"><Phone />Call Customer</button><button type="button"><Navigation />Open Route</button><div className="status-action-wrap"><button type="button" className="update-status" onClick={() => setMenuOpen(!menuOpen)}>Update Status <ChevronDown /></button>{menuOpen && <div className="status-menu">{['Assigned','Picked Up','In Transit','Delivered'].map(status => <button type="button" key={status} onClick={() => setMenuOpen(false)}>{status}</button>)}</div>}</div><button type="button" className="report-issue" onClick={() => setIssueOpen(true)}><AlertTriangle />Report Issue</button></div>{issueOpen && <div className="issue-modal" role="dialog" aria-modal="true" aria-label="Report delivery issue"><div><button type="button" onClick={() => setIssueOpen(false)} aria-label="Close issue form"><X /></button><AlertTriangle /><h3>Report an issue</h3><p>Tell the operations team what is affecting this delivery.</p><textarea placeholder="Describe the delivery issue..." /><button type="button" className="submit-issue" onClick={() => setIssueOpen(false)}>Submit Report</button></div></div>}</aside>
}

function FeatureStrip() {
  return <section className="delivery-feature-strip"><h2><Leaf />Key Features for Delivery Partners</h2><div>{deliveryFeatures.map(feature => { const Icon=featureIcons[feature.icon]; return <article key={feature.title}><span className={feature.icon==='alert'?'warning':''}><Icon /></span><div><strong>{feature.title}</strong><p>{feature.text}</p></div></article> })}</div></section>
}

export default function MyDeliveries() {
  const [filters,setFilters] = useState({search:'',status:'All Status',date:'today',area:'All Areas'})
  const [selected,setSelected] = useState(deliveries[0])
  const [page,setPage] = useState(1)
  const filtered = useMemo(() => deliveries.filter(item => { const term=filters.search.trim().toLowerCase(); const matchesSearch=!term || [item.id,item.customer,item.product,item.pickup,item.drop].some(value=>value.toLowerCase().includes(term)); return matchesSearch && (filters.status==='All Status'||item.status===filters.status) && (filters.area==='All Areas'||item.area===filters.area) && filters.date==='today' }),[filters])
  const pageItems=filtered.slice((page-1)*8,page*8)
  const changeFilters=value => { setFilters(value); setPage(1) }
  const reset=()=>{setFilters({search:'',status:'All Status',date:'today',area:'All Areas'});setPage(1)}
  return <><DeliveriesHero /><div className="my-deliveries-content"><DeliveryStats /><Filters filters={filters} setFilters={changeFilters} reset={reset} /><div className="deliveries-workspace"><DeliveriesList items={pageItems} selectedId={selected?.id} onSelect={setSelected} page={page} setPage={setPage} total={filtered.length} /><DeliveryDetails delivery={selected} onClose={()=>setSelected(null)} /></div><FeatureStrip /></div></>
}
