import { ArrowRight, Check, ChevronRight, ChevronUp, Download, FileText, Headphones, MapPin, Package, RefreshCw, ShieldCheck, Truck, Wallet, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { routes } from '../../../../config/routes'
import { formatOrderDate } from '../../data/consumerOrders.mock'
import { shopProducts } from '../../data/shopProducts.mock'
import ProductPhoto from '../ProductPhoto'

const money = value => `₹ ${value.toLocaleString('en-IN')}`
const statusStyle = {
  outForDelivery: 'bg-blue-50 text-blue-700', shipped: 'bg-blue-50 text-blue-700', processing: 'bg-amber-50 text-amber-700',
  delivered: 'bg-emerald-50 text-emerald-700', cancelled: 'bg-rose-50 text-rose-700',
}
function StatusBadge({ order }) {
  const Icon = order.status === 'delivered' ? ShieldCheck : order.status === 'cancelled' ? X : Truck
  return <span className={`inline-flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-semibold ${statusStyle[order.status]}`}><Icon size={15} />{order.statusLabel}</span>
}
function FarmThumbnail() {
  return <img src="/images/dashboard/farmer-hero.png" alt="Farm fields" className="size-[46px] shrink-0 rounded-md object-cover object-left" />
}
function TrackingTimeline({ order }) {
  if (order.status === 'cancelled') return <p id="order-tracking" className="rounded-lg bg-rose-50 p-4 text-sm text-rose-700">This order was cancelled. {order.statusDate}.</p>
  const labels = ['Confirmed', 'Packed', 'Shipped', 'Out for Delivery', 'Delivered']
  const current = { processing: 1, shipped: 2, outForDelivery: 3, delivered: 4 }[order.status] ?? 0
  const steps = order.tracking || labels.map((title, index) => ({ title, date: index === 0 ? formatOrderDate(order.placedAt).replace(', 2025', '') : index <= current ? 'Complete' : 'Pending', time: index <= current ? '' : '—' }))
  return <div id="order-tracking" className="rounded-lg border border-[#dfece5] bg-gradient-to-r from-[#f2fff6] to-white p-4"><h3 className="mb-3 flex flex-wrap items-center gap-2 text-[12px] font-bold text-[#17243b]"><Package size={17} className="text-emerald-800" />Order Tracking <span className="font-normal text-slate-500">Order #{order.id}</span></h3><ol className="relative grid grid-cols-1 gap-3 pl-2 sm:grid-cols-5 sm:gap-1 sm:pl-0"><span aria-hidden="true" className="absolute bottom-4 left-[17px] top-3 w-0.5 bg-emerald-700 sm:bottom-auto sm:left-[8%] sm:right-[8%] sm:top-[11px] sm:h-0.5 sm:w-auto" />{steps.map((step, index) => <li key={step.title} className="relative z-10 flex gap-3 text-[10px] text-[#475672] sm:block sm:text-center"><span className={`grid size-7 shrink-0 place-items-center rounded-full border-2 border-white sm:mx-auto sm:mb-2 ${index <= current ? 'bg-emerald-700 text-white' : 'bg-[#e0e8ef] text-slate-500'}`}>{index <= current ? <Check size={12} /> : <span className="size-1.5 rounded-full bg-slate-500" />}</span><span><strong className={`block text-[10px] ${index === current ? 'text-blue-700' : 'text-[#24334c]'}`}>{step.title}</strong><span className="block">{step.date}</span><span className="block">{step.time}</span></span></li>)}</ol></div>
}
function OrderedItems({ order, onAllItems }) {
  return <div className="rounded-lg border border-[#e2eaf0] p-4"><div className="flex items-center justify-between"><h3 className="text-[12px] font-bold text-[#17243b]">Ordered Items ({order.items.length})</h3><button type="button" onClick={onAllItems} className="inline-flex items-center gap-1 text-[11px] text-emerald-800 hover:underline">View All Items <ArrowRight size={14} /></button></div><div className="mt-2 grid grid-cols-3 gap-2 sm:grid-cols-5">{order.items.slice(0, 4).map((item, index) => { const product = shopProducts.find(candidate => candidate.id === item.productId); return <div key={`${item.name}-${index}`} className="min-w-0"><ProductPhoto tile={product?.tile ?? order.imageTile} alt={item.name} className="h-[78px] w-full rounded-md" /><p className="mt-1 truncate text-[10px] font-semibold text-[#22324a]">{item.name}</p><p className="text-[9px] text-slate-500">{item.pack} • {item.quantity} qty</p></div> })}{order.items.length > 4 && <button type="button" onClick={onAllItems} className="grid min-h-[78px] place-content-center rounded-md border border-[#dfe8ed] bg-[#f8fafb] text-center text-xs text-[#24334c]">+{order.items.length - 4}<small className="text-[9px] text-slate-500">more item{order.items.length - 4 === 1 ? '' : 's'}</small></button>}</div></div>
}
function OrderInformation({ order }) {
  const address = order.address || { name: 'Priya Sharma', lines: 'B-102, Sunrise Apartments', city: 'New Delhi - 110062' }
  return <div className="space-y-2"><section className="rounded-lg border border-[#dcece3] bg-gradient-to-r from-[#effcf3] to-[#f7fff9] p-4"><h3 className="flex items-center gap-1.5 text-[12px] font-bold text-[#17243b]"><ShieldCheck size={17} className="text-emerald-800" />Delivery Address: <span className="font-normal">{order.statusDate.replace('Expected by ', '').replace('Delivered on ', '')}</span></h3><div className="mt-2 flex gap-2 rounded-lg bg-white p-2 text-[10px]"><MapPin size={15} className="shrink-0 text-emerald-800" /><div className="min-w-0 flex-1"><strong className="block text-[#1a2940]">{address.name}</strong><span className="block text-slate-500">{address.lines}</span><span className="block text-slate-500">{address.city}</span></div><Link to={routes.consumer.help} className="self-start text-emerald-800 hover:underline">Change</Link></div></section><section className="rounded-lg border border-[#dcece3] bg-gradient-to-r from-[#f4fff7] to-white p-4"><h3 className="flex items-center gap-2 text-[12px] font-bold text-[#17243b]"><Wallet size={17} className="text-emerald-800" />Payment Summary</h3><dl className="mt-2 space-y-1 text-[10px]"><div className="flex justify-between"><dt className="text-slate-600">Subtotal</dt><dd>{money(order.subtotal)}</dd></div><div className="flex justify-between"><dt className="text-slate-600">Delivery Charge</dt><dd>{money(order.deliveryCharge)}</dd></div><div className="flex justify-between"><dt className="text-slate-600">Discount</dt><dd className="text-emerald-700">− {money(order.discount)}</dd></div><div className="mt-2 flex justify-between border-t border-[#dfe9e5] pt-2 text-[12px] font-bold text-[#17243b]"><dt>Total Paid</dt><dd>{money(order.total)}</dd></div></dl><p className="mt-1 text-[10px] text-slate-500">Paid via {order.paidWith}</p></section></div>
}
function OrderActions({ order, onInvoice, onReorder, onCancel }) {
  const canTrack = !['delivered', 'cancelled'].includes(order.status)
  return <div className="mt-2 grid grid-cols-2 gap-1.5 sm:flex sm:flex-wrap">{canTrack && <Link to={routes.consumer.trackOrder(order.id)} className="flex min-h-11 items-center justify-center gap-1 rounded-lg border border-emerald-700 bg-emerald-700 px-2 text-[11px] font-medium text-white hover:bg-emerald-800 sm:flex-1"><Truck size={16} />Track Order</Link>}<button type="button" onClick={() => onInvoice(order)} className="flex min-h-11 items-center justify-center gap-1 rounded-lg border border-[#cfe3dd] bg-white px-2 text-[11px] font-medium text-[#075b32] hover:bg-emerald-50 sm:flex-1"><Download size={16} />Download Invoice</button><button type="button" onClick={() => onReorder(order)} className="flex min-h-11 items-center justify-center gap-1 rounded-lg border border-[#cfe3dd] bg-white px-2 text-[11px] font-medium text-[#075b32] hover:bg-emerald-50 sm:flex-1"><RefreshCw size={16} />Reorder</button><Link to={routes.consumer.orderDetails(order.id)} className="flex min-h-11 items-center justify-center gap-1 rounded-lg border border-[#cfe3dd] bg-white px-2 text-[11px] font-medium text-[#075b32] hover:bg-emerald-50 sm:flex-1"><FileText size={16} />View Details</Link>{order.cancellation?.canCancel && <button type="button" onClick={() => onCancel(order)} className="flex min-h-11 items-center justify-center gap-1 rounded-lg border border-rose-300 bg-white px-2 text-[11px] font-medium text-rose-700 hover:bg-rose-50 sm:flex-1"><X size={16} />Cancel Order</button>}<Link to={routes.consumer.help} className="col-span-2 flex min-h-11 items-center justify-center gap-1 rounded-lg border border-[#dce7ec] bg-white px-2 text-[11px] text-[#263652] hover:bg-emerald-50 sm:flex-1"><Headphones size={16} />Need Help?</Link></div>
}
export function ExpandedOrderCard({ order, onCollapse, onDetails, onInvoice, onReorder, onCancel }) {
  return <article className="rounded-2xl border border-emerald-400 bg-white p-4 shadow-[0_2px_14px_rgba(7,91,50,.05)]"><div className="grid gap-2 pb-2 sm:grid-cols-[minmax(0,1.5fr)_minmax(120px,.75fr)_70px_minmax(125px,.8fr)] sm:items-center"><div className="flex min-w-0 gap-4"><ProductPhoto tile={order.imageTile} alt={order.summary} className="h-[82px] w-[112px] shrink-0 rounded-lg" /><div className="min-w-0"><div className="flex flex-wrap items-baseline gap-x-3"><strong className="text-[12px] text-[#17243b]">Order #{order.id}</strong><span className="text-[10px] text-slate-500">{formatOrderDate(order.placedAt)}</span></div><p className="mt-1 text-[11px] text-slate-500">{order.items.length} items · {order.summary}</p></div></div><div className="flex items-center gap-2 pl-[124px] sm:pl-0"><FarmThumbnail /><span><strong className="block text-[11px] text-[#17243b]">{order.farm}</strong><small className="block text-[10px] text-slate-500">{order.location}</small></span></div><strong className="pl-[124px] text-[12px] text-[#17243b] sm:pl-0">{money(order.total)}</strong><div className="flex items-start justify-between gap-1 pl-[124px] sm:pl-0"><span><StatusBadge order={order} /><small className="mt-1 block text-[10px] text-slate-500">{order.statusDate}</small></span><button type="button" onClick={onCollapse} aria-label={`Collapse order ${order.id}`} className="rounded p-1 hover:bg-slate-100"><ChevronUp size={16} /></button></div></div><div className="grid gap-2 lg:grid-cols-[minmax(0,2.15fr)_minmax(215px,.9fr)]"><div className="min-w-0 space-y-2"><TrackingTimeline order={order} /><OrderedItems order={order} onAllItems={() => onDetails(order)} /></div><OrderInformation order={order} /></div><OrderActions order={order} onInvoice={onInvoice} onReorder={onReorder} onCancel={onCancel} /></article>
}
export function OrderListItem({ order, onSelect }) {
  return <button type="button" onClick={() => onSelect(order.id)} aria-label={`Open order ${order.id}`} className="grid w-full gap-2 border-b border-[#e6edf0] px-2 py-1.5 text-left last:border-0 hover:bg-[#f5fcf7] sm:grid-cols-[minmax(0,1.5fr)_minmax(120px,.75fr)_70px_minmax(125px,.8fr)] sm:items-center"><div className="flex min-w-0 gap-4"><ProductPhoto tile={order.imageTile} alt={order.summary} className="h-[64px] w-[105px] shrink-0 rounded-md" /><span className="min-w-0"><span className="flex flex-wrap items-baseline gap-x-3"><strong className="text-[11px] text-[#17243b]">Order #{order.id}</strong><small className="text-[10px] text-slate-500">{formatOrderDate(order.placedAt)}</small></span><small className="mt-1 block truncate text-[10px] text-slate-500">{order.items.length} items · {order.summary}</small></span></div><span className="flex items-center gap-2 pl-[124px] sm:pl-0"><FarmThumbnail /><span><strong className="block text-[10px] text-[#17243b]">{order.farm}</strong><small className="block text-[10px] text-slate-500">{order.location}</small></span></span><strong className="pl-[124px] text-[11px] text-[#17243b] sm:pl-0">{money(order.total)}</strong><span className="flex items-center justify-between gap-1 pl-[124px] sm:pl-0"><span><StatusBadge order={order} /><small className="mt-1 block text-[9px] text-slate-500">{order.statusDate}</small></span><ChevronRight size={17} className="shrink-0 text-[#24344e]" /></span></button>
}
export function OrderDetailsDialog({ order, onClose, onInvoice, onReorder }) {
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/45 p-4" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><div role="dialog" aria-modal="true" aria-labelledby="order-details-title" className="max-h-[85vh] w-full max-w-lg overflow-y-auto rounded-xl bg-white p-5 shadow-xl"><div className="flex items-start justify-between"><div><h2 id="order-details-title" className="text-lg font-bold text-[#17243b]">Order #{order.id}</h2><p className="text-xs text-slate-500">Placed {formatOrderDate(order.placedAt)} · {order.farm}</p></div><button type="button" onClick={onClose} aria-label="Close order details" className="rounded p-1 hover:bg-slate-100"><X size={20} /></button></div><div className="mt-3"><StatusBadge order={order} /><p className="mt-1 text-xs text-slate-500">{order.statusDate}</p></div><h3 className="mt-5 text-sm font-bold text-[#17243b]">Ordered Items</h3><ul className="mt-2 divide-y divide-slate-100">{order.items.map((item, index) => { const product = shopProducts.find(candidate => candidate.id === item.productId); return <li key={`${item.name}-${index}`} className="flex items-center gap-3 py-2"><ProductPhoto tile={product?.tile ?? order.imageTile} alt={item.name} className="size-11 shrink-0 rounded-md" /><span className="flex-1 text-xs text-[#17243b]">{item.name}<small className="block text-slate-500">{item.pack} · {item.quantity} qty</small></span></li> })}</ul><div className="mt-3 flex justify-between border-t border-slate-200 pt-3 text-sm font-bold"><span>Total Paid</span><span>{money(order.total)}</span></div><div className="mt-4 flex gap-2"><button type="button" onClick={() => onInvoice(order)} className="flex flex-1 items-center justify-center gap-1 rounded-lg border border-emerald-500 py-2 text-xs font-medium text-emerald-900"><Download size={15} />Invoice</button><button type="button" onClick={() => onReorder(order)} className="flex flex-1 items-center justify-center gap-1 rounded-lg bg-emerald-700 py-2 text-xs font-medium text-white"><RefreshCw size={15} />Reorder</button></div></div></div>
}
