import { CalendarDays, ChevronRight, Clock3, Download, FileText, Headphones, Leaf, MapPin, Package, RefreshCw, Search, ShieldCheck, ShoppingBag, Star, Truck, Wallet } from 'lucide-react'
import { Link } from 'react-router-dom'
import { routes } from '../../../../config/routes'
import { orderFilterOptions } from '../../data/consumerOrders.mock'

const card = 'rounded-xl border border-[#dfe8ef] bg-white shadow-[0_2px_12px_rgba(19,77,62,.025)]'

export function OrdersHero() {
  return <section className="consumer-hero relative isolate min-h-[245px] overflow-hidden rounded-b-lg bg-emerald-50 px-6 py-8 md:px-9 md:py-10"><div className="relative z-10 max-w-[680px]"><h1 className="text-[34px] font-extrabold leading-tight tracking-tight text-[#102c25] md:text-[43px]">My Orders</h1><h2 className="text-[17px] font-bold leading-tight text-[#172c28] md:text-[21px]">Track and manage your purchases from trusted farms.</h2><p className="mt-1 text-[14px] text-[#36445e]">Real food. Real farmers. Always with you.</p><div className="mt-6 flex flex-wrap items-center gap-x-7 gap-y-2 text-[12px] text-[#213448]"><span className="flex items-center gap-2"><Leaf size={27} className="rounded-full bg-[#53ac3e] p-1 text-white" />Farm Fresh Products</span><span className="flex items-center gap-2"><ShieldCheck size={27} className="rounded-lg bg-emerald-700 p-1 text-white" />Verified Farms</span><span className="flex items-center gap-2"><Truck size={28} className="text-emerald-800" />Safe &amp; On-Time Delivery</span></div></div><p aria-hidden="true" className="absolute right-[28%] top-9 z-10 hidden -rotate-12 font-serif text-[18px] italic leading-5 text-[#112344] xl:block">Good<br />Food<br />Happy People<span className="mt-1 block h-0.5 rounded bg-emerald-700" /></p></section>
}

const stats = [
  { key: 'total', label: 'Total Orders', caption: 'Since joining KhetSetu', icon: Package },
  { key: 'active', label: 'Active Orders', caption: 'In transit or processing', icon: Truck },
  { key: 'delivered', label: 'Delivered Orders', caption: 'Successfully delivered', icon: ShieldCheck },
  { key: 'savings', label: 'Total Savings', caption: 'Saved on your orders', icon: Wallet },
]
export function OrderStats({ values }) {
  return <section aria-label="Order statistics" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ key, label, caption, icon: Icon }) => <article key={key} className={`${card} flex min-h-[140px] items-center gap-4 px-5 py-5`}><span className="grid size-[70px] shrink-0 place-items-center rounded-xl bg-gradient-to-br from-emerald-700 to-[#006838] text-white"><Icon size={30} strokeWidth={2.1} /></span><span className="min-w-0"><span className="block text-[13px] text-[#17243d]">{label}</span><strong className="block text-[28px] leading-tight text-[#101726]">{key === 'savings' ? `₹ ${values[key].toLocaleString('en-IN')}` : values[key]}</strong><small className="block truncate text-[11px] text-slate-500">{caption}</small></span></article>)}</section>
}

export function OrderFilters({ filter, onFilter, counts, dateRange, onDateRange, search, onSearch }) {
  return <div className="flex flex-col gap-3 border-b border-[#e6eff0] p-4 sm:p-5"><div role="tablist" aria-label="Order status" className="flex min-w-0 max-w-full gap-1.5 overflow-x-auto pb-1">{orderFilterOptions.map(option => <button type="button" role="tab" aria-selected={filter === option.key} key={option.key} onClick={() => onFilter(option.key)} className={`shrink-0 rounded-lg px-4 py-3 text-[13px] font-medium ${filter === option.key ? 'bg-emerald-700 text-white shadow-sm' : 'bg-[#f4f7f9] text-[#34425c] hover:bg-emerald-50'}`}>{option.label} ({counts[option.key]})</button>)}</div><div className="flex w-full flex-wrap gap-3"><label className="relative flex h-11 min-w-[160px] items-center rounded-lg border border-[#dfe7ed] bg-white pl-2.5"><CalendarDays size={16} className="shrink-0 text-[#263955]" /><select aria-label="Order date range" value={dateRange} onChange={event => onDateRange(event.target.value)} className="w-full appearance-none bg-transparent px-2 pr-5 text-[11px] text-[#24344e] outline-none"><option value="3">Last 3 Months</option><option value="1">Last Month</option><option value="all">All Dates</option></select><ChevronRight size={13} className="pointer-events-none absolute right-2 rotate-90 text-[#263955]" /></label><label className="flex h-11 min-w-[220px] flex-1 items-center gap-2 rounded-lg border border-[#dfe7ed] bg-white px-2.5 sm:max-w-[360px]"><Search size={16} className="shrink-0 text-[#263955]" /><input aria-label="Search orders" value={search} onChange={event => onSearch(event.target.value)} placeholder="Search orders..." className="min-w-0 flex-1 bg-transparent text-[11px] outline-none" /></label></div></div>
}

const featureRows = [
  { title: 'Order Tracking', detail: 'Track your orders in real-time', icon: Truck, target: '#order-tracking' },
  { title: 'Order History', detail: 'View and manage all your orders', icon: Clock3, target: '#orders-list' },
  { title: 'Delivery Status', detail: 'Get live delivery updates', icon: MapPin, target: '#order-tracking' },
  { title: 'Invoice Download', detail: 'Download invoices anytime', icon: Download, action: 'invoice' },
  { title: 'Reorder Easily', detail: 'Order your favorite products again', icon: RefreshCw, action: 'reorder' },
  { title: 'Ratings & Reviews', detail: 'Rate products and support farmers', icon: Star, target: routes.consumer.reviews },
  { title: 'Support Help', detail: 'Get help with your orders', icon: Headphones, target: routes.consumer.help },
  { title: 'Farm Passport Access', detail: 'Know your food. Know your farmer.', icon: Leaf, target: routes.consumer.farmPassport },
]
export function OrdersAside({ onInvoice, onReorder }) {
  return <aside className="min-w-0 space-y-5"><section className="rounded-xl border border-[#ddede3] bg-gradient-to-br from-white to-[#f0fff3] p-5"><h2 className="flex items-center gap-3 border-b border-[#dcece3] pb-2 text-[17px] font-bold text-[#172238]"><Star size={27} className="fill-emerald-700 text-emerald-700" />Key Features</h2><div className="divide-y divide-[#e2eee7]">{featureRows.map(({ title, detail, icon: Icon, target, action }) => { const content = <><span className="grid size-11 shrink-0 place-items-center rounded-lg bg-[#e3fae9] text-emerald-800"><Icon size={19} /></span><span className="min-w-0 flex-1"><strong className="block text-[11px] text-[#17243b]">{title}</strong><small className="block text-[10px] leading-4 text-slate-500">{detail}</small></span><ChevronRight size={16} className="shrink-0 text-emerald-800" /></>; const classes = 'flex min-h-[64px] w-full items-center gap-2.5 py-1.5 text-left hover:bg-emerald-50'; return action ? <button type="button" key={title} onClick={action === 'invoice' ? onInvoice : onReorder} className={classes}>{content}</button> : target.startsWith('#') ? <a key={title} href={target} className={classes}>{content}</a> : <Link key={title} to={target} className={classes}>{content}</Link> })}</div></section><section className={`${card} p-5`}><h2 className="flex items-center gap-2 text-[13px] font-bold text-[#17243b]"><Leaf size={19} className="fill-emerald-600 text-emerald-700" />Why Shop with Confidence?</h2><div className="mt-2 grid gap-1.5 sm:grid-cols-2 xl:grid-cols-2">{[[ShieldCheck, 'Verified Products', '100% farm-sourced and quality checked'], [Leaf, 'Farm Fresh', 'Straight from farms to your home'], [ShoppingBag, 'Farm Traceability', 'Know your farmer with Farm Passport'], [FileText, 'Secure Payments', 'Safe and encrypted transactions']].map(([Icon, title, detail]) => <div key={title} className="flex gap-2 rounded-lg bg-[#f5fcf7] p-1.5"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-[#e3f7e9] text-emerald-800"><Icon size={18} /></span><span><strong className="block text-[10px] text-[#17243b]">{title}</strong><small className="block text-[9px] leading-3 text-slate-500">{detail}</small></span></div>)}</div></section><section className={`${card} p-5`}><h2 className="flex items-center gap-2 text-[13px] font-bold text-[#17243b]"><Headphones size={21} className="text-emerald-700" />Need Help with Your Order?</h2><p className="mt-1 pl-7 text-[10px] leading-4 text-slate-500">Our support team is here to help you with any queries about your orders.</p><Link to={routes.consumer.help} className="mt-2 flex h-8 items-center justify-center gap-2 rounded-lg border border-emerald-500 text-[11px] font-medium text-emerald-900 hover:bg-emerald-50">Contact Support <ChevronRight size={14} /></Link></section></aside>
}
