import { ChevronDown, ChevronLeft, ChevronRight, EllipsisVertical, Leaf } from 'lucide-react'
import Card from '../../../../components/ui/Card'
import ProductBadge from './ProductBadge'
import ProductImage from './ProductImage'
import ProductMobileCard from './ProductMobileCard'

export default function ProductsTable({ pageProducts, filteredCount, page, pageCount, onPageChange, selectedIds, onToggle, onSelectPage, sort, onSortChange, onProductOpen }) {
  const allSelected = pageProducts.length > 0 && pageProducts.every(product => selectedIds.has(product.id))
  const from = filteredCount ? (page - 1) * 8 + 1 : 0
  const to = Math.min(page * 8, filteredCount)

  return <Card className="flex min-w-0 flex-col p-4">
    <div className="flex min-h-10 items-center justify-between gap-3"><h2 className="text-lg font-bold text-slate-900">Products ({filteredCount})</h2><label className="flex items-center gap-1.5 text-xs whitespace-nowrap text-slate-500">Sort by:<span className="sr-only">Sort products</span><select value={sort} onChange={event => onSortChange(event.target.value)} className="appearance-none bg-transparent pr-1 font-medium text-slate-700 outline-none"><option value="newest">Newest First</option><option value="oldest">Oldest First</option><option value="name">Name A–Z</option><option value="priceHigh">Price: High to Low</option><option value="priceLow">Price: Low to High</option></select><ChevronDown className="size-3.5 text-slate-700" /></label></div>
    <div className="mt-1 hidden overflow-x-auto md:block"><table className="w-full min-w-[810px] table-fixed text-left text-[11px] text-slate-700"><colgroup><col className="w-[4%]" /><col className="w-[19%]" /><col className="w-[10%]" /><col className="w-[10%]" /><col className="w-[11%]" /><col className="w-[12%]" /><col className="w-[15%]" /><col className="w-[13%]" /><col className="w-[6%]" /></colgroup><thead><tr className="h-[42px] rounded-lg bg-slate-50 text-[10px] font-medium text-slate-600"><th className="pl-1"><input type="checkbox" checked={allSelected} onChange={onSelectPage} aria-label="Select all products on this page" className="size-4 accent-emerald-700" /></th><th>Product</th><th>Category</th><th>Quantity</th><th>Unit Price</th><th>Stock Status</th><th>Batch ID</th><th>Listing Status</th><th className="text-center">Actions</th></tr></thead><tbody>{pageProducts.map(product => <tr key={product.id} tabIndex={0} onClick={() => onProductOpen(product)} onKeyDown={event => { if (event.key === 'Enter') onProductOpen(product) }} className="h-[70px] cursor-pointer border-b border-slate-200/80 transition hover:bg-emerald-50/60 last:border-0"><td className="pl-1"><input type="checkbox" checked={selectedIds.has(product.id)} onClick={event => event.stopPropagation()} onChange={() => onToggle(product.id)} aria-label={`Select ${product.name}`} className="size-4 accent-emerald-700" /></td><td><div className="flex items-center gap-2"><ProductImage product={product} className="size-[46px]" /><span className="min-w-0"><strong className="block truncate text-[11px] text-slate-900">{product.name}</strong><small className="text-[10px] text-slate-500">{product.packageSize}</small></span></div></td><td><ProductBadge kind="category" value={product.category} /></td><td>{product.quantity} {product.quantityUnit}</td><td className="font-semibold whitespace-nowrap">₹ {product.unitPrice} / {product.priceUnit}</td><td><ProductBadge kind="stock" value={product.stockStatus} /></td><td><span className="inline-flex items-center gap-1 rounded-lg border border-slate-200 bg-slate-50 px-1.5 py-1 text-[10px] whitespace-nowrap"><Leaf className="size-3 fill-emerald-600 text-emerald-700" />{product.batchId}</span></td><td><ProductBadge kind="listing" value={product.listingStatus} /></td><td className="text-center"><button type="button" onClick={event => event.stopPropagation()} aria-label={`More actions for ${product.name}`} className="rounded-lg p-1 hover:bg-slate-100"><EllipsisVertical className="size-4" /></button></td></tr>)}</tbody></table></div>
    <div className="mt-2 grid gap-2 md:hidden">{pageProducts.map(product => <ProductMobileCard key={product.id} product={product} selected={selectedIds.has(product.id)} onToggle={onToggle} onOpen={() => onProductOpen(product)} />)}</div>
    {filteredCount === 0 && <p className="py-14 text-center text-sm text-slate-500">No products match these filters.</p>}
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 pt-5 text-xs text-slate-500"><p>Showing {from}–{to} of {filteredCount} products</p><nav aria-label="Product pages" className="flex items-center gap-1.5"><button type="button" onClick={() => onPageChange(page - 1)} disabled={page === 1} aria-label="Previous page" className="grid size-9 place-items-center rounded-lg border border-slate-200 text-slate-700 disabled:opacity-40"><ChevronLeft className="size-4" /></button>{Array.from({ length: pageCount }, (_, index) => <button type="button" key={index} onClick={() => onPageChange(index + 1)} aria-label={`Page ${index + 1}`} aria-current={page === index + 1 ? 'page' : undefined} className={`grid size-9 place-items-center rounded-lg border text-xs ${page === index + 1 ? 'border-emerald-700 bg-emerald-700 text-white' : 'border-slate-200 bg-white text-slate-700'}`}>{index + 1}</button>)}<button type="button" onClick={() => onPageChange(page + 1)} disabled={page === pageCount} aria-label="Next page" className="grid size-9 place-items-center rounded-lg border border-slate-200 text-slate-700 disabled:opacity-40"><ChevronRight className="size-4" /></button></nav></div>
  </Card>
}
