import { ArrowRight, Bookmark, CalendarDays, ChevronRight, Clock3, CreditCard, Leaf, LockKeyhole, MapPin, Minus, Plus, ReceiptText, ShieldCheck, ShoppingCart, Star, Tag, Trash2, Truck, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import ProductPhoto from '../ProductPhoto'
import ProduceImage from '../ProduceImage'
import { shopProducts } from '../../data/shopProducts.mock'
import { routes } from '../../../../config/routes'

const money = value => `₹ ${Math.round(value).toLocaleString('en-IN')}`
const card = 'rounded-xl border border-[#dce9ef] bg-white shadow-[0_3px_16px_rgba(25,80,65,0.025)]'

export function CartCheckoutHeader() {
  return <header className="flex flex-wrap items-center justify-between gap-4 px-2 pb-4 pt-1">
    <div><h1 className="flex items-center gap-2 text-[30px] font-extrabold leading-tight tracking-tight text-slate-950 sm:text-[36px]">Cart &amp; Checkout <Leaf className="size-7 fill-[#73bd45] text-[#369432]" /></h1><p className="text-[15px] text-slate-600">Farm fresh products, just a few steps away from your home.</p></div>
    <div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-[13px] text-slate-700"><span className="hidden -rotate-12 text-center font-serif text-lg italic leading-4 text-[#101b41] xl:block">Good<br />Food<br />Happy People<span className="mt-1 block h-0.5 rotate-[-10deg] rounded-full bg-emerald-700" /></span><span className="flex items-center gap-2"><Truck className="size-6 fill-emerald-700 text-emerald-700" />Freshly Delivered</span><span className="flex items-center gap-2"><ShieldCheck className="size-6 fill-emerald-700 text-emerald-700" />Farm Verified</span><span className="flex items-center gap-2"><Leaf className="size-6 fill-emerald-700 text-emerald-700" />Chemical Free</span></div>
  </header>
}

const steps = [['Cart', 'Review your items'], ['Address', 'Choose delivery address'], ['Payment', 'Select payment method'], ['Review', 'Confirm and place order']]
export function CheckoutProgress({ current = 1 }) {
  return <nav aria-label="Checkout progress" className={`${card} mb-4 overflow-x-auto px-3 py-3 sm:px-7`}><ol className="flex min-w-[480px] items-start">{steps.map(([name, description], index) => <li key={name} aria-current={current === index + 1 ? 'step' : undefined} className="relative flex-1 text-center"><div className="relative mx-auto mb-1.5 flex items-center justify-center"><span className={`relative z-10 grid size-9 place-items-center rounded-full text-base font-semibold ${current >= index + 1 ? 'bg-emerald-800 text-white' : 'bg-slate-200 text-slate-700'}`}>{index + 1}</span>{index < 3 && <span className={`absolute left-[calc(50%+25px)] right-[-50%] top-1/2 h-[2px] -translate-y-1/2 ${current > index + 1 ? 'bg-emerald-700' : 'bg-slate-200'}`} />}</div><p className="text-sm font-semibold text-slate-900">{name}</p><p className="text-xs text-slate-500">{description}</p></li>)}</ol></nav>
}

function QuantityControl({ item, onQuantity }) {
  return <div className="inline-flex h-9 items-center overflow-hidden rounded-lg border border-[#d5e3ee] text-sm text-[#13213c]"><button type="button" aria-label={`Decrease ${item.name} quantity`} onClick={() => onQuantity(item.key, item.quantity - 1)} disabled={item.quantity <= 1} className="grid h-full w-8 place-items-center bg-[#f8fbfd] hover:bg-emerald-50 disabled:opacity-40"><Minus size={15} /></button><span className="grid h-full min-w-9 place-items-center border-x border-[#d5e3ee] font-semibold">{item.quantity}</span><button type="button" aria-label={`Increase ${item.name} quantity`} onClick={() => onQuantity(item.key, item.quantity + 1)} className="grid h-full w-8 place-items-center bg-[#f8fbfd] hover:bg-emerald-50"><Plus size={15} /></button></div>
}

function CartItemRow({ item, onQuantity, onRemove, onSave }) {
  const product = shopProducts.find(candidate => candidate.name === item.name || (item.name === 'Wild Honey' && candidate.name === 'Wild Forest Honey'))
  const label = product?.category === 'Jaggery' ? 'Natural' : product?.category === 'Grains' ? 'Organic' : 'Farm Fresh'
  return <div className="grid gap-3 border-b border-[#e4edf2] py-3 last:border-0 md:grid-cols-[minmax(0,1.5fr)_minmax(125px,1fr)_76px_112px_76px_112px] md:items-center md:gap-2">
    <div className="flex min-w-0 items-center gap-3">{item.name === 'Organic Turmeric' ? <ProduceImage tile={5} alt={item.name} className="size-[72px] shrink-0 rounded-lg" /> : <ProductPhoto tile={product?.tile ?? 0} alt={item.name} className="size-[72px] shrink-0 rounded-lg" />}<div className="min-w-0"><p className="truncate text-[13px] font-semibold text-[#0e1930]">{item.name}</p><p className="text-xs text-slate-500">{item.pack}</p><span className="mt-1 inline-flex items-center gap-1 rounded-full bg-[#ddf9e9] px-2 py-0.5 text-[11px] text-emerald-900"><Leaf size={11} fill="currentColor" />{label}</span></div></div>
    <div className="pl-[84px] text-xs md:pl-0"><p className="font-medium text-[#152442]">{product?.farm || 'Verified Farm'}</p><span className="mt-0.5 inline-flex items-center gap-1 rounded-full bg-[#e0f9e9] px-1.5 py-0.5 text-[11px] text-emerald-900"><ShieldCheck size={12} fill="currentColor" />Verified Farm</span><p className="mt-1 flex items-center gap-1 text-[11px] text-slate-500"><MapPin size={11} />{product?.location || 'India'}</p></div>
    <div className="flex items-center justify-between pl-[84px] md:block md:pl-0"><span className="text-xs text-slate-500 md:hidden">Price</span><div><p className="text-[15px] font-bold text-[#0e1930]">{money(item.price)}</p><p className="text-[11px] text-slate-500">per {item.pack}</p></div></div>
    <div className="flex items-center justify-between pl-[84px] md:block md:pl-0"><span className="text-xs text-slate-500 md:hidden">Quantity</span><QuantityControl item={item} onQuantity={onQuantity} /></div>
    <div className="flex items-center justify-between pl-[84px] md:block md:pl-0"><span className="text-xs text-slate-500 md:hidden">Subtotal</span><p className="text-[15px] font-bold text-[#0e1930]">{money(item.price * item.quantity)}</p></div>
    <div className="flex gap-4 pl-[84px] text-[11px] text-slate-600 md:flex-col md:gap-1 md:pl-0"><button type="button" onClick={() => onRemove(item.key)} className="inline-flex items-center gap-1 hover:text-rose-600"><Trash2 size={15} />Remove</button><button type="button" onClick={() => onSave(item.key)} className="inline-flex items-center gap-1 hover:text-emerald-800"><Bookmark size={15} />Save for later</button></div>
  </div>
}

export function CartItemsCard({ cartItems, savedItems, onQuantity, onRemove, onSave, onRestore, onClear }) {
  return <section className={`${card} p-3 sm:p-4`}><div className="mb-3 flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-[17px] font-bold text-[#10203c]"><ShoppingCart className="size-6 text-emerald-700" />Your Cart ({cartItems.length} {cartItems.length === 1 ? 'item' : 'items'})</h2>{cartItems.length > 0 && <button type="button" onClick={onClear} className="inline-flex items-center gap-1.5 text-xs text-slate-600 hover:text-rose-600"><Trash2 size={16} />Clear Cart</button>}</div>
    {cartItems.length ? <><div className="hidden grid-cols-[minmax(0,1.5fr)_minmax(125px,1fr)_76px_112px_76px_112px] gap-2 rounded-lg bg-[#f3f8fb] px-2 py-2 text-xs text-slate-600 md:grid"><span>Product</span><span>Farm / Seller</span><span>Price</span><span>Quantity</span><span>Subtotal</span><span /></div><div className="px-1">{cartItems.map(item => <CartItemRow key={item.key} item={item} onQuantity={onQuantity} onRemove={onRemove} onSave={onSave} />)}</div></> : <div className="rounded-lg bg-[#f4fbf7] px-5 py-10 text-center"><ShoppingCart className="mx-auto size-10 text-emerald-700" /><h3 className="mt-2 text-lg font-bold">Your cart is empty</h3><p className="mt-1 text-sm text-slate-600">Start shopping from verified farms and discover fresh products.</p><Link to={routes.consumer.products} className="mt-4 inline-flex rounded-lg bg-emerald-800 px-5 py-2 text-sm font-semibold text-white">Continue Shopping</Link></div>}
    {savedItems.length > 0 && <div className="mt-3 border-t border-slate-200 pt-3"><h3 className="text-sm font-bold text-[#10203c]">Saved for later</h3><div className="mt-2 flex flex-wrap gap-2">{savedItems.map(item => <button key={item.key} type="button" onClick={() => onRestore(item.key)} className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-900">{item.name} · Move to cart</button>)}</div></div>}
  </section>
}

export function DeliveryAddressCard({ addresses, selectedId, onSelect, onAdd }) {
  return <section id="delivery-address" className={`${card} p-3.5`}><div className="mb-3 flex items-start justify-between gap-2"><div className="flex gap-2"><MapPin className="size-6 shrink-0 fill-emerald-700 text-emerald-700" /><div><h2 className="font-bold text-[#10203c]">Delivery Address</h2><p className="mt-0.5 text-xs text-slate-500">Select Delivery Address</p></div></div><button type="button" onClick={onAdd} className="inline-flex shrink-0 items-center gap-1 text-xs text-emerald-900 hover:underline">Manage Addresses <ArrowRight size={14} /></button></div><div className="space-y-2">{addresses.map(address => <button type="button" key={address.id} onClick={() => onSelect(address.id)} className={`flex w-full gap-3 rounded-lg border px-3 py-2 text-left text-xs ${selectedId === address.id ? 'border-emerald-500 bg-[#f0fff6]' : 'border-[#dbe6ed] bg-white hover:bg-emerald-50'}`}><span className={`mt-0.5 grid size-4 shrink-0 place-items-center rounded-full border ${selectedId === address.id ? 'border-emerald-700 bg-emerald-700' : 'border-slate-300'}`}>{selectedId === address.id && <span className="size-1.5 rounded-full bg-white" />}</span><span><span className="font-bold text-[#122039]">{address.label}</span>{address.default && <span className="ml-2 rounded-full bg-[#d6f8e3] px-2 py-0.5 text-[11px] text-emerald-900">Default</span>}<span className="mt-1 block leading-4 text-slate-600">{address.lines}</span><span className="block text-slate-600">{address.name} | {address.phone}</span></span></button>)}</div><button type="button" onClick={onAdd} className="mt-2 flex w-full items-center justify-center gap-1 rounded-lg border border-emerald-600 py-1.5 text-xs font-semibold text-emerald-900 hover:bg-emerald-50"><Plus size={15} />Add New Address</button></section>
}

export function DeliverySlotCard({ dates, date, onDate, time, onTime }) {
  const slots = ['9:00 AM – 12:00 PM', '12:00 PM – 3:00 PM', '3:00 PM – 6:00 PM', '6:00 PM – 9:00 PM']
  return <section id="delivery-slot" className={`${card} p-3.5`}><div className="mb-2 flex gap-2"><CalendarDays className="size-6 text-emerald-700" /><div><h2 className="font-bold text-[#10203c]">Delivery Slot</h2><p className="mt-0.5 text-xs text-slate-500">Choose your preferred delivery time</p></div></div><div className="grid grid-cols-4 gap-1.5">{dates.map(day => <button type="button" key={day.key} onClick={() => onDate(day.key)} className={`rounded-md border px-1 py-1.5 text-center text-[11px] leading-4 ${date === day.key ? 'border-emerald-700 bg-emerald-800 text-white' : 'border-[#dce8ef] text-slate-700 hover:bg-emerald-50'}`}>{day.label}<br />{day.display}</button>)}</div><div className="mt-2 space-y-0.5">{slots.map(slot => <button key={slot} type="button" onClick={() => onTime(slot)} className={`flex w-full items-center gap-2 rounded-md px-2 py-1 text-left text-xs ${time === slot ? 'border border-emerald-500 bg-[#f3fff6]' : 'border border-transparent hover:bg-emerald-50'}`}><span className={`grid size-3.5 place-items-center rounded-full border ${time === slot ? 'border-emerald-700 bg-emerald-700' : 'border-slate-400'}`}>{time === slot && <span className="size-1.5 rounded-full bg-white" />}</span><span className="flex-1 font-medium text-[#20314e]">{slot}</span><span className="rounded bg-[#e1f9eb] px-2 text-[10px] font-semibold text-emerald-800">FREE</span></button>)}</div><p className="mt-2 flex items-start gap-2 text-[11px] leading-4 text-slate-600"><Clock3 size={16} className="shrink-0 text-emerald-700" />Fresh products are delivered in temperature controlled conditions.</p></section>
}

const features = [[UsersRound, 'Quantity Management', 'Easily update quantities or remove items', 'cart-items'], [MapPin, 'Address Selection', 'Choose or add delivery address', 'delivery-address'], [CalendarDays, 'Delivery Slot', 'Pick a convenient delivery time', 'delivery-slot'], [Tag, 'Promo Code', 'Apply offers and save more', 'promo-code'], [CreditCard, 'Payment Options', 'Multiple secure payment methods', 'order-summary'], [ReceiptText, 'Order Summary', 'Clear breakdown of all charges', 'order-summary']]
export function CheckoutFeatures() {
  return <section className="rounded-xl border border-[#e0f2e8] bg-gradient-to-br from-white to-[#f0fff5] p-3"><h2 className="flex items-center gap-2 border-b border-[#dcece5] pb-2 text-[16px] font-bold text-[#10203c]"><Star className="size-7 fill-emerald-700 text-emerald-700" />Important Components</h2><div>{features.map(([Icon, title, description, anchor]) => <a key={title} href={`#${anchor}`} className="flex items-center gap-3 border-b border-[#e1eee8] px-1 py-2 last:border-0 hover:bg-emerald-50"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-[#e0f9e9] text-emerald-800"><Icon size={19} fill={title === 'Promo Code' ? 'currentColor' : 'none'} /></span><span className="min-w-0 flex-1"><span className="block text-[12px] font-semibold text-[#15213b]">{title}</span><span className="block text-[11px] leading-4 text-slate-500">{description}</span></span><ChevronRight size={16} className="shrink-0 text-emerald-800" /></a>)}</div></section>
}

export function PromoCodeCard({ code, setCode, applied, message, onApply, onRemove }) {
  return <section id="promo-code" className={`${card} p-3`}><h2 className="mb-3 flex items-center gap-2 text-sm font-bold text-[#10203c]"><Tag className="size-5 fill-emerald-700 text-emerald-700" />Apply Promo Code</h2><form onSubmit={event => { event.preventDefault(); onApply() }} className="flex gap-2"><input aria-label="Promo code" value={code} onChange={event => setCode(event.target.value)} placeholder="Enter promo code (e.g. KISAN10)" className="min-w-0 flex-1 rounded-lg border border-[#d7e5ee] px-3 py-2 text-xs outline-none focus:border-emerald-600" /><button type="submit" className="rounded-lg bg-emerald-800 px-4 py-2 text-xs font-semibold text-white hover:bg-emerald-900">Apply</button></form>{message && <p role="status" className={`mt-2 text-xs ${applied ? 'text-emerald-800' : 'text-rose-600'}`}>{message}{applied && <button type="button" onClick={onRemove} className="ml-2 underline">Remove</button>}</p>}</section>
}

export function OrderSummary({ count, subtotal, fee, savings, promoDiscount, payable, disabled, error, onProceed }) {
  return <section id="order-summary" className={`${card} p-3`}><h2 className="mb-3 flex items-center gap-2 border-b border-[#e3ebf0] pb-2 text-[16px] font-bold text-[#10203c]"><ReceiptText className="size-6 text-emerald-700" />Order Summary</h2><div className="space-y-2 text-[13px] text-slate-600"><div className="flex justify-between"><span>Item Total ({count} {count === 1 ? 'item' : 'items'})</span><strong className="text-[#10203c]">{money(subtotal)}</strong></div><div className="flex justify-between"><span>Delivery Fee</span><strong className="text-[#10203c]">{money(fee)}</strong></div><div className="flex justify-between text-emerald-800"><span>Total Savings</span><strong>− {money(savings)}</strong></div>{promoDiscount > 0 && <div className="flex justify-between text-emerald-800"><span>Promo Discount</span><strong>− {money(promoDiscount)}</strong></div>}</div><div className="mt-4 flex items-center justify-between rounded-lg bg-[#e5faee] px-3 py-3 text-[15px] font-bold text-[#092d1b]"><span>Total Payable</span><span className="text-xl">{money(payable)}</span></div>{error && <p role="alert" className="mt-2 text-xs text-rose-600">{error}</p>}<button type="button" disabled={disabled} onClick={onProceed} className="mt-3 flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-800 py-3 text-sm font-semibold text-white hover:bg-emerald-900 disabled:cursor-not-allowed disabled:opacity-50">Proceed to Payment <ArrowRight size={17} /></button><p className="mt-2 flex items-center justify-center gap-1.5 text-[11px] text-slate-500"><ShieldCheck size={16} className="text-emerald-700" />100% Secure &amp; Encrypted Payments</p></section>
}

export function CheckoutTrustStrip() {
  const items = [[ShieldCheck, 'Verified Products', '100% farm-sourced and quality checked'], [LockKeyhole, 'Secure Payments', 'Your transactions are always safe'], [Leaf, 'Freshness Guaranteed', 'Farm fresh to your home'], [UsersRound, 'Support Farmers', 'Your purchase empowers farmers']]
  return <section className="mt-4 grid gap-3 rounded-xl bg-gradient-to-r from-[#e6fae9] to-[#edfff3] px-4 py-3 sm:grid-cols-2 xl:grid-cols-[1.2fr_repeat(4,1fr)]"><div className="flex items-center gap-2 text-sm font-bold text-[#102c20]"><Leaf className="size-7 fill-emerald-700 text-emerald-700" />Shop with Confidence</div>{items.map(([Icon, title, description]) => <div key={title} className="flex items-center gap-2 border-l border-[#cfebd9] pl-3"><Icon className="size-7 shrink-0 text-emerald-800" /><div><p className="text-[11px] font-bold text-[#11243a]">{title}</p><p className="text-[10px] leading-3 text-slate-600">{description}</p></div></div>)}</section>
}
