import { Heart, ShieldCheck, ShoppingCart, Star, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { routes } from '../../../config/routes'
import ProductPhoto from './ProductPhoto'

export default function ConsumerProductCard({ product, view, wished, onWish, onAdd }) {
  const photo = <ProductPhoto tile={product.tile} alt={product.name} className="aspect-square w-full rounded-lg" />
  return <article className={`flex min-w-0 rounded-xl border border-slate-200 bg-white p-1.5 shadow-sm ${view === 'list' ? 'flex-row gap-4' : 'flex-col'}`}><div className={`relative shrink-0 ${view === 'list' ? 'w-36 sm:w-44' : 'w-full'}`}>{product.slug ? <Link to={routes.consumer.productDetail} aria-label={`View ${product.name}`}>{photo}</Link> : photo}{product.badge && <span className="absolute left-2 top-2 rounded-full bg-amber-100 px-2 py-1 text-[10px] font-semibold text-amber-950">{product.badge}</span>}<button type="button" aria-label={`${wished ? 'Remove' : 'Add'} ${product.name} ${wished ? 'from' : 'to'} wishlist`} aria-pressed={wished} onClick={() => onWish(product.id)} className="absolute right-2 top-2 grid size-8 place-items-center rounded-full bg-white text-slate-700 shadow"><Heart size={17} fill={wished ? '#ef4444' : 'none'} className={wished ? 'text-red-500' : ''} /></button></div><div className="flex min-w-0 flex-1 flex-col px-2 pb-1.5 pt-2"><h3 className="truncate text-[13px] font-bold text-slate-950">{product.slug ? <Link to={routes.consumer.productDetail} className="hover:text-emerald-800 hover:underline">{product.name}</Link> : product.name}</h3><p className="truncate text-[11px] text-slate-500">{product.farm} &nbsp;•&nbsp; {product.location}</p><p className="text-[11px] text-slate-600">{product.quantity}</p><div className="mt-1 flex flex-wrap items-center gap-2"><strong className="text-lg leading-none text-slate-950">₹ {product.price}</strong><del className="text-xs text-slate-400">₹ {product.originalPrice}</del><span className="inline-flex items-center gap-0.5 rounded-full bg-emerald-100 px-2 py-0.5 text-[11px] font-semibold text-emerald-800"><TrendingUp size={11} />{product.discount}%</span></div><div className="mt-1 flex flex-wrap items-center justify-between gap-1 text-[11px]"><span className="inline-flex items-center gap-1 text-slate-800"><Star size={14} className="fill-amber-500 text-amber-500" /><strong>{product.rating}</strong><span className="text-slate-500">({product.reviews})</span></span>{product.verified && <span className="inline-flex items-center gap-1 text-emerald-800"><ShieldCheck size={14} fill="currentColor" />Verified</span>}</div><button type="button" onClick={() => onAdd(product)} className="mt-auto flex h-9 w-full items-center justify-center gap-2 rounded-md bg-emerald-700 text-xs font-medium text-white hover:bg-emerald-800"><ShoppingCart size={15} />Add to Cart</button></div></article>
}
