import { ShoppingCart, Star, Tag, TrendingUp } from 'lucide-react'
import { routes } from '../../../config/routes'
import { Link } from 'react-router-dom'
import { products } from '../data/dashboard.mock'
import ProduceImage from './ProduceImage'
import SectionTitle from './SectionTitle'

export default function FeaturedProducts({ onAdd, addedIds, search = '' }) {
  const visible = products.filter(product => `${product.name} ${product.farm}`.toLowerCase().includes(search.toLowerCase()))
  return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><SectionTitle icon={Tag} title="Featured Products" to={routes.consumer.products} action="View All Products" /><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{visible.map(product => <article key={product.id} className="min-w-0 rounded-lg border border-slate-200 p-2.5"><div className="relative"><ProduceImage tile={product.tile} alt={product.name} className="aspect-square w-full rounded-md" /><span className="absolute right-1 top-1 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-semibold text-amber-950">{product.badge}</span></div><div className="px-1 pt-2.5"><h3 className="truncate text-sm font-semibold text-slate-950">{product.id === 2 ? <Link to={routes.consumer.productDetail} className="hover:text-emerald-800 hover:underline">{product.name}</Link> : product.name}</h3><p className="truncate text-[11px] text-slate-500">{product.quantity} &nbsp;|&nbsp; {product.farm}</p><div className="mt-1 flex flex-wrap items-center gap-x-2"><strong className="text-sm text-slate-950">₹ {product.price}</strong><del className="text-[11px] text-slate-400">₹ {product.originalPrice}</del><span className="inline-flex items-center gap-0.5 rounded-full bg-emerald-100 px-1.5 text-[10px] font-semibold text-emerald-800"><TrendingUp size={10} />{product.discount}%</span></div><p className="flex items-center gap-1 text-[11px]"><Star size={12} className="fill-amber-500 text-amber-500" />{product.rating} <span className="text-slate-500">({product.reviews})</span></p><button type="button" onClick={() => onAdd(product.id)} className={`mt-2 flex h-[34px] w-full items-center justify-center gap-1.5 rounded-md text-xs font-medium text-white ${addedIds.includes(product.id) ? 'bg-emerald-950' : 'bg-emerald-800 hover:bg-emerald-700'}`}><ShoppingCart size={13} />{addedIds.includes(product.id) ? 'Added to Cart' : 'Add to Cart'}</button></div></article>)}{visible.length === 0 && <p className="col-span-full py-5 text-center text-sm text-slate-500">No featured products match your search.</p>}</div></section>
}
