import { BadgeCheck, Droplet, FlaskConical, Heart, Leaf, Minus, Plus, ShieldCheck, ShoppingCart, Star, Truck, Zap } from 'lucide-react'
import { useState } from 'react'
import { gheeProduct } from '../data/productDetail.mock'
import { useConsumerCommerce } from '../state/useConsumerCommerce'

export default function ProductPurchasePanel({ onAdd, onBuy }) {
  const [packIndex, setPackIndex] = useState(1)
  const [quantity, setQuantity] = useState(1)
  const { wishlist, toggleWishlist } = useConsumerCommerce()
  const wished = wishlist.includes(gheeProduct.name)
  const pack = gheeProduct.packs[packIndex]
  return <section className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-md bg-emerald-700 px-2.5 py-1 text-xs font-semibold text-white">Bestseller</span><span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-900"><ShieldCheck size={15} fill="currentColor" className="text-emerald-700" />Chemical Free</span></div>
    <h1 className="mt-3 text-[28px] font-extrabold leading-tight text-slate-950">{gheeProduct.name}</h1><p className="text-sm text-slate-500">{gheeProduct.tagline}</p>
    <div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-sm"><Star size={18} className="fill-amber-500 text-amber-500" /><strong>{gheeProduct.rating}</strong><span className="text-slate-500">({gheeProduct.reviews} reviews)</span><span className="border-l border-slate-200 pl-3 text-slate-500">{gheeProduct.boughtThisMonth}+ bought this month</span></div>
    <div className="mt-2 flex flex-wrap items-center gap-3"><strong className="text-[27px] leading-none text-slate-950">₹ {pack.price.toLocaleString('en-IN')}</strong><del className="text-sm text-slate-500">₹ {packIndex === 1 ? gheeProduct.originalPrice : Math.round(pack.price * 1.11).toLocaleString('en-IN')}</del><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">{packIndex === 1 ? 12 : 10}% OFF</span></div><p className="mt-1 text-xs text-slate-500">(₹ {pack.price} / {pack.label})</p>
    <p className="mt-3 text-[13px] leading-[1.45] text-slate-600">{gheeProduct.description}</p>
    <div className="mt-3 grid grid-cols-2 gap-2 border-y border-slate-200 py-2.5 text-center text-[10px] text-slate-600 sm:grid-cols-4"><span className="flex items-center justify-center gap-1"><Droplet size={17} className="text-emerald-700" />100% Pure</span><span className="flex items-center justify-center gap-1"><FlaskConical size={17} className="text-emerald-700" />No Preservatives</span><span className="flex items-center justify-center gap-1"><Leaf size={17} className="text-emerald-700" />Traditional Bilona</span><span className="flex items-center justify-center gap-1"><BadgeCheck size={17} className="text-emerald-700" />Farm Fresh</span></div>
    <div className="mt-3 flex flex-wrap justify-between gap-4"><div><h2 className="mb-1.5 text-xs font-bold text-slate-950">Pack Size</h2><div className="flex gap-1.5">{gheeProduct.packs.map((option, index) => <button type="button" key={option.label} aria-pressed={packIndex === index} onClick={() => setPackIndex(index)} className={`min-w-[74px] rounded-lg border px-2 py-1.5 text-center text-xs ${packIndex === index ? 'border-emerald-700 bg-emerald-50 font-semibold text-emerald-900' : 'border-slate-200 text-slate-700'}`}>{option.label}<span className="block">₹ {option.price.toLocaleString('en-IN')}</span></button>)}</div></div><div><h2 className="mb-1.5 text-xs font-bold text-slate-950">Quantity</h2><div className="flex h-[44px] items-center rounded-lg border border-slate-200"><button type="button" aria-label="Decrease quantity" onClick={() => setQuantity(value => Math.max(1, value - 1))} className="grid h-full w-9 place-items-center bg-slate-50"><Minus size={15} /></button><span className="w-12 text-center text-sm font-semibold">{quantity}</span><button type="button" aria-label="Increase quantity" onClick={() => setQuantity(value => Math.min(99, value + 1))} className="grid h-full w-9 place-items-center bg-slate-50 text-emerald-800"><Plus size={15} /></button></div></div></div>
    <p className="mt-2 text-xs text-emerald-700">● &nbsp;Ready to ship</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => onAdd({ ...gheeProduct, price: pack.price, pack: pack.label }, quantity)} className="flex h-10 min-w-[135px] flex-1 items-center justify-center gap-2 rounded-lg bg-emerald-700 text-sm font-semibold text-white hover:bg-emerald-800"><ShoppingCart size={18} />Add to Cart</button><button type="button" onClick={() => onBuy({ ...gheeProduct, price: pack.price, pack: pack.label }, quantity)} className="flex h-10 min-w-[135px] flex-1 items-center justify-center gap-2 rounded-lg bg-emerald-900 text-sm font-semibold text-white hover:bg-emerald-950"><Zap size={18} fill="currentColor" />Buy Now</button><button type="button" aria-label={wished ? 'Remove A2 Cow Ghee from wishlist' : 'Add A2 Cow Ghee to wishlist'} aria-pressed={wished} onClick={() => toggleWishlist(gheeProduct.name)} className="grid size-10 shrink-0 place-items-center rounded-full border border-slate-200 text-rose-500"><Heart size={19} fill={wished ? 'currentColor' : 'none'} /></button></div>
    <div className="mt-4 grid gap-2 text-[10px] text-slate-600 sm:grid-cols-3 sm:gap-0 sm:divide-x sm:divide-slate-200"><span className="flex items-center gap-1 sm:pr-2"><Truck size={19} className="shrink-0 text-emerald-700" />Estimated delivery<br />Apr 28 – Apr 30, 2025</span><span className="flex items-center gap-1 sm:px-2"><ShieldCheck size={19} className="shrink-0 text-emerald-700" />7-day easy returns<br />Replacement or refund</span><span className="flex items-center gap-1 sm:pl-2"><ShieldCheck size={19} className="shrink-0 text-emerald-700" />Secure checkout<br />100% safe & secure</span></div>
  </section>
}
