import { ArrowRight, ChevronRight, Droplet, FlaskConical, Leaf, LayoutGrid, MapPin, ShieldCheck, Sprout } from 'lucide-react'
import { Link } from 'react-router-dom'
import { routes } from '../../../config/routes'
import { gheeFeatures, gheeProduct } from '../data/productDetail.mock'

const featureIcons = [ShieldCheck, Sprout, Droplet, FlaskConical, ShieldCheck]
export default function ProductFarmAside() {
  return <aside className="min-w-0 space-y-3"><section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="mb-2 flex items-center gap-2 text-sm font-bold text-slate-950"><LayoutGrid size={19} className="text-emerald-800" />From Our Farm</h2><div className="flex gap-3"><img src="/images/dashboard/farmer-hero.png" alt="Sundar Farms farmer" className="h-[128px] w-[115px] shrink-0 rounded-lg object-cover object-right" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1"><strong className="text-sm text-slate-950">{gheeProduct.farm.name}</strong><span className="inline-flex items-center gap-1 rounded-full bg-emerald-100 px-1.5 py-0.5 text-[10px] text-emerald-900"><ShieldCheck size={12} />Verified Farm</span></div><p className="mt-1.5 flex items-center gap-1 text-xs text-slate-500"><MapPin size={13} />{gheeProduct.farm.location}</p><p className="mt-1.5 flex items-center gap-1 text-xs text-slate-500"><Sprout size={13} />Farming since {gheeProduct.farm.since}</p><Link to={routes.consumer.farmPassport} className="mt-2 flex h-8 items-center justify-center gap-1 rounded-lg bg-emerald-50 text-xs font-medium text-emerald-900 hover:bg-emerald-100">View Farm Details <ArrowRight size={15} /></Link></div></div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-4"><div className="mb-2 flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-bold text-slate-950"><Leaf size={20} className="text-emerald-800" />Farm Passport</h2><Link to={routes.consumer.farmPassport} className="flex items-center gap-1 text-xs text-emerald-900">View Full Passport <ArrowRight size={15} /></Link></div><div className="flex gap-3"><img src="/images/consumer/farm-passport-qr.png" alt="Sundar Farms batch passport QR code" className="size-[96px] shrink-0 rounded border border-slate-200 object-contain p-1" /><dl className="grid min-w-0 grid-cols-[auto_minmax(0,1fr)] gap-x-3 gap-y-1 text-[11px]"><dt className="text-slate-500">Batch ID</dt><dd className="truncate">{gheeProduct.passport.batch}</dd><dt className="text-slate-500">Source</dt><dd className="truncate">{gheeProduct.passport.source}</dd><dt className="text-slate-500">Processed</dt><dd>{gheeProduct.passport.processed}</dd><dt className="text-slate-500">Traceability</dt><dd>{gheeProduct.passport.traceability}</dd></dl></div><p className="mt-2 flex items-center gap-2 rounded-lg bg-emerald-50 p-2 text-[11px] text-slate-600"><Leaf size={20} className="shrink-0 text-emerald-800" />Scan the QR code on your product pack to see the full farm story, farmer details, and certifications.</p></section>
    <section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="mb-2 flex items-center gap-2 text-sm font-bold text-slate-950"><Leaf size={20} className="text-emerald-800" />Key Features</h2><div className="space-y-2">{gheeFeatures.map((feature, index) => { const Icon = featureIcons[index]; return <div key={feature.title} className="flex min-h-[58px] items-center gap-2 rounded-lg border border-slate-200 px-2"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-emerald-100 text-emerald-800"><Icon size={17} /></span><span className="min-w-0 flex-1"><strong className="block truncate text-xs text-slate-900">{feature.title}</strong><small className="block truncate text-[10px] text-slate-500">{feature.detail}</small></span><ChevronRight size={15} className="text-slate-600" /></div> })}</div></section></aside>
}
