import { ArrowRight, Leaf, ShoppingCart, Star, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { routes } from '../../../config/routes'
import { relatedProducts } from '../data/productDetail.mock'
import ProduceImage from './ProduceImage'
import ProductPhoto from './ProductPhoto'
export default function RelatedProducts({ onAdd }) {
  return <section className="rounded-xl border border-slate-200 bg-white p-4"><div className="mb-2 flex items-center justify-between"><h2 className="flex items-center gap-2 text-base font-bold text-slate-950"><Leaf size={21} className="text-emerald-800" />Related Products</h2><Link to={routes.consumer.products} className="flex items-center gap-1 text-xs text-emerald-900">View All <ArrowRight size={15} /></Link></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{relatedProducts.map(product => <article key={product.id} className="flex min-w-0 gap-2 rounded-lg border border-slate-200 p-2">{product.photoSource === 'shop' ? <ProductPhoto tile={product.tile} alt={product.name} className="h-[120px] w-[100px] shrink-0 rounded-md" /> : <ProduceImage tile={product.tile} alt={product.name} className="h-[120px] w-[100px] shrink-0 rounded-md" />}<div className="min-w-0 flex-1"><h3 className="truncate text-xs font-semibold text-slate-950">{product.name}</h3><p className="truncate text-[10px] text-slate-500">{product.detail}</p><div className="flex flex-wrap items-center gap-1"><strong className="text-xs">₹ {product.price}</strong><del className="text-[10px] text-slate-400">₹ {product.originalPrice}</del><span className="inline-flex items-center rounded-full bg-emerald-100 px-1 text-[10px] text-emerald-800"><TrendingUp size={9} />{product.discount}%</span></div><p className="flex items-center gap-1 text-[10px]"><Star size={11} className="fill-amber-500 text-amber-500" />{product.rating} <span className="text-slate-500">({product.reviews})</span></p><button type="button" onClick={() => onAdd(product)} className="mt-2 flex w-full items-center justify-center gap-1 rounded-md bg-emerald-100 py-1 text-[10px] font-medium text-emerald-900 hover:bg-emerald-200"><ShoppingCart size={12} />Add to Cart</button></div></article>)}</div></section>
}
