import { ArrowRight, BarChart3, ChevronRight, Heart, Leaf, LayoutGrid, Search, ShieldCheck, ShoppingCart, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import { routes } from '../../../config/routes'
const features = [
  { title: 'Smart Search', detail: 'Find products, farms or keywords', icon: Search },
  { title: 'Category Filters', detail: 'Browse by product categories', icon: LayoutGrid },
  { title: 'Verified Products', detail: '100% farm-sourced & quality checked', icon: ShieldCheck },
  { title: 'Price Comparison', detail: 'Compare and get the best value', icon: BarChart3 },
  { title: 'Wishlist', detail: 'Save your favorite products', icon: Heart },
  { title: 'Easy Cart Access', detail: 'Quick and secure checkout', icon: ShoppingCart },
]
export default function ShopProductsAside({ cart }) {
  return <aside className="min-w-0 space-y-3"><section className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex items-center gap-3"><ShoppingCart size={32} className="text-emerald-800" /><div className="flex-1"><h2 className="text-sm font-bold text-slate-950">My Cart</h2><strong className="text-xl text-slate-950">₹ {cart.total.toLocaleString('en-IN')}</strong></div><span className="rounded-full bg-emerald-700 px-2.5 py-1 text-xs font-medium text-white">{cart.count} items</span><ChevronRight size={17} /></div><Link to={routes.consumer.cart} className="mt-3 flex h-9 w-full items-center justify-center rounded-md bg-emerald-700 text-xs font-medium text-white hover:bg-emerald-800">View Cart</Link></section><section className="rounded-xl border border-emerald-100 bg-[#f2fcf5] p-3 shadow-sm"><h2 className="mb-2 flex items-center gap-2 text-sm font-bold text-slate-950"><Star size={22} fill="currentColor" className="text-emerald-800" />Key Features</h2><div className="divide-y divide-emerald-100 rounded-lg border border-emerald-100 bg-white/55 px-2">{features.map(feature => { const Icon = feature.icon; return <div key={feature.title} className="flex min-h-[54px] items-center gap-2.5"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-emerald-100 text-emerald-800"><Icon size={19} /></span><span className="min-w-0 flex-1"><strong className="block truncate text-[11px] text-slate-900">{feature.title}</strong><small className="block truncate text-[10px] text-slate-500">{feature.detail}</small></span><ChevronRight size={14} className="text-emerald-900" /></div> })}</div></section><section className="relative min-h-[215px] overflow-hidden rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><h2 className="relative z-10 flex items-center gap-2 text-sm font-bold text-slate-950"><Leaf size={22} className="text-emerald-800" />From Our Farms to Your Home</h2><p className="relative z-10 mt-2 text-xs text-slate-600">Pure. Fresh. Verified. Always.</p><ul className="relative z-10 mt-3 space-y-1 text-[11px] text-slate-700">{['Direct from verified farmers', 'No harmful chemicals', 'Freshly packed and delivered', 'Support rural communities'].map(item => <li key={item} className="flex items-center gap-2"><span className="grid size-4 place-items-center rounded-full bg-emerald-600 text-white">✓</span>{item}</li>)}</ul><div className="absolute inset-x-0 bottom-0 h-[72px] bg-[url('/images/consumer/promo.png')] bg-cover bg-bottom" /><Link to={routes.consumer.dashboard} className="sr-only">Go to Dashboard <ArrowRight size={14} /></Link></section></aside>
}
