export const routes = {
  auth: {
    login: '/login',
    signup: '/signup',
  },
  consumer: {
    dashboard: '/consumer/dashboard',
    products: '/consumer/products',
    productDetail: '/consumer/products/a2-cow-ghee',
    cart: '/consumer/cart',
    payment: '/consumer/checkout/payment',
    orders: '/consumer/orders',
    subscriptions: '/consumer/subscriptions',
    farmPassport: '/consumer/farm-passport',
    wishlist: '/consumer/wishlist',
    reviews: '/consumer/reviews',
    profile: '/consumer/profile',
    help: '/consumer/help',
  },
  farmer: {
    dashboard: '/farmer/dashboard',
    farm: '/farmer/farm',
    products: '/farmer/products',
    orders: '/farmer/orders',
    cropDoctor: '/farmer/crop-doctor',
    priceInsights: '/farmer/price-insights',
    agriStores: '/farmer/agri-stores',
    earnings: '/farmer/earnings',
    messages: '/farmer/messages',
    profile: '/farmer/profile',
    profileFarmBasics: '/farmer/profile/farm-basics',
    profileVerification: '/farmer/profile/verification',
    profileComplete: '/farmer/profile/complete',
    help: '/farmer/help',
  },
  delivery: {
    dashboard: '/delivery/dashboard',
    deliveries: '/delivery/deliveries',
    routeMap: '/delivery/route-map',
    earnings: '/delivery/earnings',
    history: '/delivery/history',
    profile: '/delivery/profile',
    help: '/delivery/help',
  },
}
