import { useState } from 'react'
import { X } from 'lucide-react'

export default function QuotationDialog({ request, onClose, onSend }) {
  const [quantity, setQuantity] = useState('1')
  const [price, setPrice] = useState('')
  const [message, setMessage] = useState(`We can supply ${request.product} for your ${request.crop.toLowerCase()} crop.`)
  return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/45 p-4" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section role="dialog" aria-modal="true" aria-labelledby="quotation-title" className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl sm:p-6"><div className="flex items-start justify-between gap-3"><div><h2 id="quotation-title" className="text-xl font-bold text-[#17243e]">Send Quotation / Offer</h2><p className="mt-1 text-sm text-[#657592]">{request.name} · {request.product}</p></div><button type="button" onClick={onClose} aria-label="Close quotation" className="grid size-9 place-items-center rounded-lg hover:bg-slate-100"><X size={20} /></button></div><form onSubmit={event => { event.preventDefault(); onSend(request, { quantity: Number(quantity), price: Number(price), message: message.trim() }) }} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-[#344761]">Quantity<input required min="1" type="number" value={quantity} onChange={event => setQuantity(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-[#d7e4ed] px-3 outline-none focus:border-emerald-600" /></label><label className="text-sm font-medium text-[#344761]">Offer price (₹)<input required min="1" type="number" value={price} onChange={event => setPrice(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-[#d7e4ed] px-3 outline-none focus:border-emerald-600" /></label><label className="text-sm font-medium text-[#344761] sm:col-span-2">Message<textarea required rows={4} value={message} onChange={event => setMessage(event.target.value)} className="mt-1 w-full rounded-lg border border-[#d7e4ed] p-3 outline-none focus:border-emerald-600" /></label><div className="flex justify-end gap-3 sm:col-span-2"><button type="button" onClick={onClose} className="min-h-10 rounded-lg border border-[#d7e4ed] px-4 text-sm">Cancel</button><button type="submit" className="min-h-10 rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white hover:bg-emerald-800">Save Offer</button></div></form></section></div>
}
