import { ArrowRight, BadgeCheck, Bell, Check, ClipboardList, FileText, Package, Phone, ShieldAlert, Star } from 'lucide-react'
import { ShopkeeperAvatar } from '../ShopkeeperImage'

const card = 'min-w-0 rounded-2xl border border-[#dce8ee] bg-white p-4 shadow-sm'

export function PendingResponses({ requests, onViewAll, onSelect }) {
  return <section className={card}><div className="mb-3 flex items-start justify-between gap-2"><div className="flex items-start gap-2"><Bell size={23} className="shrink-0 text-amber-500" /><div><h2 className="text-[14px] font-bold text-[#17243e]">Pending Responses</h2><p className="text-[11px] text-[#697b96]">Requests awaiting your response</p></div></div><button type="button" onClick={onViewAll} className="flex shrink-0 items-center gap-1 text-[11px] text-emerald-800 hover:underline">View All <ArrowRight size={14} /></button></div><div className="divide-y divide-[#e7edf2] overflow-hidden rounded-lg border border-[#e4edf1]">{requests.slice(0, 3).map(request => <button key={request.id} type="button" onClick={() => onSelect(request)} className="flex min-h-[57px] w-full items-center gap-2 px-2 text-left hover:bg-emerald-50"><ShopkeeperAvatar tile={request.avatarTile} name={request.name} className="size-9" /><span className="min-w-0 flex-1"><strong className="block truncate text-[11px] text-[#17243e]">{request.name}</strong><small className="block truncate text-[10px] text-[#687995]">{request.crop} - {request.issue}</small></span><span className="shrink-0 text-right"><small className="block text-[10px] text-[#687995]">{request.time}</small><small className="mt-1 inline-block rounded-full bg-[#fff3dc] px-2 py-0.5 text-[9px] text-[#ad6c0c]">{request.priority}</small></span></button>)}</div></section>
}

export function FulfilledRequests({ requests, onViewAll, onSelect }) {
  return <section className={card}><div className="mb-3 flex items-start justify-between gap-2"><div className="flex items-start gap-2"><BadgeCheck size={23} className="shrink-0 fill-emerald-700 text-emerald-700" /><div><h2 className="text-[14px] font-bold text-[#17243e]">Recently Fulfilled Requests</h2><p className="text-[11px] text-[#697b96]">Successfully responded and farmers purchased</p></div></div><button type="button" onClick={onViewAll} className="flex shrink-0 items-center gap-1 text-[11px] text-emerald-800 hover:underline">View All <ArrowRight size={14} /></button></div><div className="divide-y divide-[#e7edf2] overflow-hidden rounded-lg border border-[#e4edf1]">{requests.slice(0, 3).map(request => <button key={request.id} type="button" onClick={() => onSelect(request)} className="flex min-h-[57px] w-full items-center gap-2 px-2 text-left hover:bg-emerald-50"><ShopkeeperAvatar tile={request.avatarTile} name={request.name} className="size-9" /><span className="min-w-0 flex-1"><strong className="block truncate text-[11px] text-[#17243e]">{request.name}</strong><small className="block truncate text-[10px] text-[#687995]">{request.crop} - {request.issue}</small></span><span className="shrink-0 text-right"><small className="block text-[10px] text-[#687995]">{request.time}</small><small className="mt-1 inline-block rounded-full bg-[#e3f9eb] px-2 py-0.5 text-[9px] text-[#157040]">Completed</small></span></button>)}</div></section>
}

const featureIcons = { file: FileText, product: Package, stock: ClipboardList, status: Check, phone: Phone, alert: ShieldAlert }
export function RequestKeyFeatures({ features }) {
  return <section className={card}><h2 className="mb-3 flex items-center gap-2 text-[14px] font-bold text-[#17243e]"><Star size={23} className="fill-emerald-700 text-emerald-700" />Key Features</h2><div className="grid gap-1">{features.map(feature => { const Icon = featureIcons[feature.icon]; return <div key={feature.title} className="flex min-h-[43px] items-center gap-2 rounded-lg bg-[#f0faf5] px-2 py-1"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-[#def7e7] text-emerald-800"><Icon size={17} /></span><span className="min-w-0"><strong className="block text-[10px] leading-tight text-[#17243e]">{feature.title}</strong><small className="block text-[9px] leading-tight text-[#677894]">{feature.detail}</small></span></div> })}</div></section>
}
