import { ArrowRight, BarChart3, Bell, Box, Package, ShieldAlert, Star, UsersRound, Zap } from 'lucide-react'
import { Link } from 'react-router-dom'
import { routes } from '../../../config/routes'
import { ShopkeeperAvatar, ShopkeeperProductImage } from './ShopkeeperImage'

const statIcons = { package: Box, users: UsersRound, sales: BarChart3, star: Star }
const statTones = {
  green: 'from-[#1ba457] to-[#08713b]',
  blue: 'from-[#49a5ff] to-[#1763da]',
  amber: 'from-[#ffc54a] to-[#f19a05]',
}

export function ShopkeeperHero() {
  return <section className="relative isolate min-h-[112px] overflow-hidden bg-[url('/images/dashboard/farmer-hero.png')] bg-[length:160%_auto] bg-[position:left_61%] px-5 py-5 sm:px-7"><div className="absolute inset-0 -z-10 bg-gradient-to-r from-white via-white/90 to-white/20" /><div className="relative z-10"><h1 className="text-[32px] font-extrabold leading-tight tracking-tight text-[#131c2d] sm:text-[37px]">Dashboard</h1><p className="text-[14px] text-[#526587]">Support farmers with the right agri-inputs and manage your store operations.</p></div><p aria-hidden="true" className="absolute right-[18%] top-3 hidden -rotate-6 font-serif text-[16px] font-semibold italic leading-tight text-[#16223b] xl:block">Help Farmers<br />Grow Better<br />Brighter Futures Together</p><p aria-hidden="true" className="absolute right-4 top-3 hidden text-[13px] font-bold leading-tight text-[#133d2b] 2xl:block">Better<br />Farms<br />Brighter<br />Futures</p></section>
}

export function ShopkeeperStatCard({ stat }) {
  const Icon = statIcons[stat.icon]
  return <article className="flex min-h-[96px] items-center gap-4 rounded-lg border border-[#dbe8ef] bg-white px-4 py-3 shadow-[0_2px_12px_rgba(24,78,75,0.03)]"><span className={`grid size-[60px] shrink-0 place-items-center rounded-lg bg-gradient-to-br text-white ${statTones[stat.tone]}`}><Icon size={31} fill={stat.icon === 'star' ? 'currentColor' : 'none'} strokeWidth={1.9} /></span><div className="min-w-0"><p className="truncate text-[13px] text-[#4b5b7b]">{stat.label}</p><div className="flex flex-nowrap items-center gap-1.5"><strong className={`whitespace-nowrap font-bold leading-tight text-[#15213d] ${stat.icon === 'sales' ? 'text-[22px]' : 'text-[25px]'}`}>{stat.value}</strong><span className={`whitespace-nowrap rounded-full px-1.5 py-0.5 text-[11px] font-semibold ${stat.icon === 'users' ? 'bg-[#fff0f0] text-[#e22532]' : 'bg-[#e7f9ed] text-[#087943]'}`}>↑ {stat.trend}</span></div><p className="truncate text-[12px] text-[#667796]">{stat.detail}</p></div></article>
}

export function PanelHeading({ icon: Icon, title, to, action = 'View All', children }) {
  return <div className="mb-2 flex min-h-[27px] items-center justify-between gap-2"><h2 className="flex min-w-0 items-center gap-2 text-[15px] font-bold text-[#182240]"><Icon size={23} className={`shrink-0 ${Icon === Zap ? 'text-amber-500' : 'text-emerald-800'}`} fill={Icon === Star || Icon === Bell ? 'currentColor' : 'none'} />{title}</h2>{children ?? (to && <Link to={to} className="shrink-0 text-[11px] font-medium text-[#22559b] hover:underline">{action}</Link>)}</div>
}

const priorityStyles = {
  High: 'bg-[#ffe7e9] text-[#d4202c]',
  Medium: 'bg-[#fff0d7] text-[#bd7212]',
  Low: 'bg-[#e4f8ed] text-[#187543]',
}

export function FarmerRequestsTable({ requests, onRespond }) {
  return <section className="min-w-0 rounded-lg border border-[#dbe8ef] bg-white p-3 shadow-sm"><PanelHeading icon={UsersRound} title="Recent Farmer Requests" to={routes.shopkeeper.requests} />
    <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[510px] table-fixed text-left text-[11px] text-[#172342]"><thead className="bg-[#f4f9fd] text-[10px] text-[#3e4f72]"><tr>{[['Farmer Name', '23%'], ['Crop / Issue', '18%'], ['Requested Product', '20%'], ['Priority', '12%'], ['Date', '12%'], ['Action', '15%']].map(([heading, width]) => <th key={heading} style={{ width }} className="border-b border-[#e3edf2] px-1.5 py-2 font-medium">{heading}</th>)}</tr></thead><tbody>{requests.map(request => <tr key={request.id} className="border-b border-[#e9eff4] last:border-0"><td className="px-1 py-1.5"><div className="flex items-center gap-1.5"><ShopkeeperAvatar tile={request.avatarTile} name={request.name} className="size-9" /><span className="min-w-0"><strong className="block truncate font-semibold">{request.name}</strong><small className="block truncate text-[10px] text-[#627494]">{request.location}</small></span></div></td><td className="px-1.5 py-1.5"><strong className="block font-medium">{request.crop}</strong><small className="block truncate text-[10px] text-[#657696]">{request.issue}</small></td><td className="px-1.5 py-1.5 font-medium">{request.product}</td><td className="px-1.5 py-1.5"><span className={`inline-flex min-w-[50px] justify-center rounded-md px-2 py-1 font-medium ${priorityStyles[request.priority]}`}>{request.priority}</span></td><td className="px-1.5 py-1.5 text-[#536486]">{request.date}<small className="block">{request.time}</small></td><td className="px-1 py-1.5"><button type="button" onClick={() => onRespond(request)} className="rounded-md bg-[#e3f8ee] px-2 py-1.5 font-medium text-[#12683e] hover:bg-emerald-200">Respond</button></td></tr>)}</tbody></table>{requests.length === 0 && <p className="py-8 text-center text-sm text-slate-500">No requests match your search.</p>}</div>
    <div className="space-y-2 md:hidden">{requests.map(request => <article key={request.id} className="rounded-lg border border-[#e5edf3] p-3"><div className="flex items-center gap-2"><ShopkeeperAvatar tile={request.avatarTile} name={request.name} className="size-9" /><div className="min-w-0 flex-1"><strong className="block text-xs">{request.name}</strong><small className="text-[11px] text-slate-500">{request.location}</small></div><span className={`rounded-md px-2 py-1 text-xs ${priorityStyles[request.priority]}`}>{request.priority}</span></div><p className="mt-2 text-xs text-[#263650]">{request.crop} · {request.issue}</p><p className="mt-1 text-xs text-[#263650]">Requested: <strong>{request.product}</strong></p><div className="mt-2 flex items-center justify-between"><small className="text-slate-500">{request.date} · {request.time}</small><button type="button" onClick={() => onRespond(request)} className="rounded-md bg-[#e3f8ee] px-3 py-1.5 text-xs font-medium text-[#12683e]">Respond</button></div></article>)}{requests.length === 0 && <p className="py-8 text-center text-sm text-slate-500">No requests match your search.</p>}</div>
  </section>
}

export function InventoryHighlights({ items }) {
  return <section className="min-w-0 rounded-lg border border-[#dbe8ef] bg-white p-3 shadow-sm"><PanelHeading icon={Package} title="Inventory Highlights" to={routes.shopkeeper.inventory} /><div className="flex items-center justify-between border-b border-[#edf1f4] py-1"><strong className="text-[12px] text-[#1b2944]">Low Stock Items</strong><span className="grid size-5 place-items-center rounded-full bg-[#f23d40] text-[11px] font-bold text-white">3</span></div><div>{items.map(item => <Link to={`${routes.shopkeeper.inventory}?stock=low`} key={item.id} className="flex items-center gap-2 border-b border-[#edf1f4] py-2 last:border-0 hover:bg-[#f6fcfa]"><ShopkeeperProductImage tile={item.tile} name={item.name} className="size-10 rounded-md" /><span className="min-w-0 flex-1"><strong className="block truncate text-[11px] text-[#14213d]">{item.name}</strong><small className="block text-[10px] text-[#607291]">{item.remaining}</small></span><span className="rounded-md bg-[#ffe9eb] px-2 py-1 text-[10px] text-[#cc2c36]">Low Stock</span></Link>)}</div><Link to={routes.shopkeeper.inventory} className="mt-2 flex items-center gap-2 rounded-lg bg-[#edfdf4] px-3 py-2"><span className="grid size-9 place-items-center rounded-md bg-[#e0f8e9] text-emerald-800"><Package size={23} /></span><span><strong className="block text-[17px] leading-none text-[#172342]">96</strong><small className="text-[10px] text-[#537d70]">Products in Stock</small></span><ArrowRight size={15} className="ml-auto text-emerald-800" /></Link><div className="mt-2 grid grid-cols-2 gap-2"><Link to={`${routes.shopkeeper.inventory}?stock=out`} className="flex items-center gap-2 rounded-lg bg-[#fff7e8] px-2 py-2"><ShieldAlert size={24} className="text-amber-500" /><span><strong className="block text-[14px] leading-none">10</strong><small className="text-[10px] text-slate-600">Out of Stock</small></span></Link><Link to={`${routes.shopkeeper.inventory}?stock=low`} className="flex items-center gap-2 rounded-lg bg-[#fff7e8] px-2 py-2"><ShieldAlert size={24} className="text-amber-500" /><span><strong className="block text-[14px] leading-none">4</strong><small className="text-[10px] text-slate-600">Running Low</small></span></Link></div></section>
}
