import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { BarChart3, Box, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CirclePause, Edit3, Eye, Leaf, MapPin, Package, Share2, ShieldCheck, ShoppingCart, Star, TrendingUp, Warehouse, X } from 'lucide-react'
import FarmerPageHero from '../components/FarmerPageHero'
import ProductImage from '../products/components/ProductImage'
import { products } from '../products/data/products.mock'
import '../products/product-details.css'

const featureItems=[
  {icon:Box,title:'Stock Management',text:'Update stock, manage inventory'},
  {icon:BarChart3,title:'Listing Performance',text:'View views, orders and earnings'},
  {icon:ShoppingCart,title:'Order History',text:'Track and manage all orders'},
  {icon:TrendingUp,title:'Price Suggestions (AI)',text:'Get best market price for your product'},
  {icon:Eye,title:'Product Visibility',text:'See how your product is performing'},
  {icon:Star,title:'Customer Reviews',text:'Build trust with buyer feedback'},
  {icon:Share2,title:'Share Product',text:'Share listing with more buyers'},
]

function DetailPanelTitle({icon:Icon,title,action}){return <header className="product-detail-panel-title"><h2><Icon/>{title}</h2>{action}</header>}

function ProductGallery({product,imageIndex,setImageIndex}){const images=product.detail.images;const move=step=>setImageIndex(index=>(index+step+images.length)%images.length);return <div className="product-gallery"><div className="product-gallery-main"><ProductImage product={{...product,image:images[imageIndex]}} className="product-gallery-image"/><span className="gallery-organic"><Leaf/> {product.detail.tags[0]}</span><button type="button" onClick={()=>move(-1)} aria-label="Previous product image"><ChevronLeft/></button><button type="button" onClick={()=>move(1)} aria-label="Next product image"><ChevronRight/></button></div><div className="product-thumbnails">{images.map((image,index)=><button key={`${image}-${index}`} type="button" onClick={()=>setImageIndex(index)} className={index===imageIndex?'active':''}><ProductImage product={{...product,image}} className="product-thumbnail-image"/></button>)}</div></div>}

function ProductInfo({product,status,expanded,setExpanded,onStock,onToggle,navigate}){const detail=product.detail;return <div className="product-info"><div className="product-title-row"><div><h2>{product.name}</h2><p>{product.category} <ChevronRight/> {detail.subcategory}</p></div><span className={status}><i/>{status==='active'?'Active':'Inactive'}</span></div><div className="product-summary-boxes"><article><BadgeIcon icon={TrendingUp}/><div><small>Price per Unit</small><strong>₹ {detail.price.toLocaleString('en-IN')}</strong><p>per {detail.priceUnit}</p></div></article><article><BadgeIcon icon={Box}/><div><small>Available Stock</small><strong>{detail.inventory.available} {detail.inventory.unit}</strong><p>({detail.inventory.availableKg} kg)</p></div></article><article><BadgeIcon icon={CalendarDays}/><div><small>Harvest Date</small><strong>{formatDate(detail.harvestDate)}</strong><p>Last Harvest</p></div></article></div><div className="product-source"><MapPin/><span><small>Farm / Source</small><strong>{detail.source}</strong></span></div><div className="product-tags">{detail.tags.map((tag,index)=><span key={tag}>{index===2?<CheckCircle2/>:<Leaf/>}{tag}</span>)}</div><p className={`product-description ${expanded?'expanded':''}`}>{detail.description}</p><button type="button" className="read-more" onClick={()=>setExpanded(value=>!value)}>{expanded?'Read Less':'Read More'} <ChevronRight/></button><div className="product-detail-actions"><button type="button" onClick={()=>navigate('/farmer/products')}><Edit3/>Edit Product</button><button type="button" className="primary" onClick={onStock}><Package/>Update Stock</button><button type="button" className="pause" onClick={onToggle}><CirclePause/>{status==='active'?'Pause Listing':'Resume Listing'}</button><button type="button" onClick={()=>navigate('/farmer/orders')}><ShoppingCart/>View Orders</button></div></div>}

function BadgeIcon({icon:Icon}){return <span><Icon/></span>}
const formatDate=value=>new Date(`${value}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})

function ProductKeyFeatures(){return <aside className="product-detail-features"><DetailPanelTitle icon={Star} title="Key Features"/><div>{featureItems.map(({icon:Icon,title,text})=><article key={title}><Icon/><span><strong>{title}</strong><small>{text}</small></span><ChevronRight/></article>)}</div></aside>}

function InventorySummary({product}){const data=product.detail.inventory;const items=[{title:'Total Stock',value:data.total,kg:data.totalKg,tone:'blue',icon:Warehouse},{title:'Reserved (Orders)',value:data.reserved,kg:data.reservedKg,tone:'orange',icon:Package},{title:'Available Stock',value:data.available,kg:data.availableKg,tone:'green',icon:Box}];return <section className="product-lower-panel inventory-summary"><DetailPanelTitle icon={Box} title="Inventory Summary" action={<button>View Details <ChevronRight/></button>}/><div>{items.map(({title,value,kg,tone,icon:Icon})=><article className={tone} key={title}><Icon/><small>{title}</small><strong>{value} {data.unit}</strong><p>{kg} kg</p></article>)}</div></section>}

function RecentOrders({product}){return <section className="product-lower-panel recent-product-orders"><DetailPanelTitle icon={ShoppingCart} title="Recent Orders" action={<button>View All Orders <ChevronRight/></button>}/><div className="orders-grid header"><span>Order ID</span><span>Buyer</span><span>Date</span><span>Quantity</span><span>Status</span></div>{product.detail.recentOrders.map(order=><div className="orders-grid" key={order.id}><span>{order.id}</span><span>{order.buyer}</span><span>{order.date}</span><span>{order.quantity}</span><em className={order.status.toLowerCase()}>{order.status}</em></div>)}</section>}

function RatingsPanel({product}){const rating=product.detail.rating;const [review,setReview]=useState(0);return <section className="product-lower-panel ratings-panel"><DetailPanelTitle icon={Star} title="Customer Ratings & Reviews" action={<button>View All <ChevronRight/></button>}/><div className="ratings-content"><div className="rating-summary"><div><Star/><span><strong>{rating.average} / 5</strong><small>Based on {rating.count} reviews</small></span></div>{rating.distribution.map((percent,index)=><p key={index}><span>{5-index} ★</span><i><b style={{width:`${percent}%`}}/></i><em>{percent}%</em></p>)}</div><div className="review-card"><header><span>{rating.reviewer[0]}</span><div><strong>{rating.reviewer}</strong><em>★★★★★</em><small>{rating.date}</small></div></header><p>“{rating.text}”</p><footer><button type="button" onClick={()=>setReview(value=>Math.max(0,value-1))}><ChevronLeft/></button><span>{[0,1,2,3].map(index=><i className={index===review?'active':''} key={index}/>)}</span><button type="button" onClick={()=>setReview(value=>Math.min(3,value+1))}><ChevronRight/></button></footer></div></div></section>}

function PriceInsights({product}){const data=product.detail.priceInsight;const position=((data.current-data.low)/(data.high-data.low))*100;return <section className="product-lower-panel price-insight-panel"><DetailPanelTitle icon={BarChart3} title="Price Insights" action={<button>View Market Trends <ChevronRight/></button>}/><div><p><strong>₹ {data.current.toLocaleString('en-IN')} <small>/ {data.unit}</small></strong><em>↗ +{data.change}%</em><span>vs last month</span></p><small>Market range in your region</small><div className="market-range"><i/><b style={{left:`${position}%`}}/></div><footer><span>₹ {data.low.toLocaleString('en-IN')}</span><strong>₹ {data.current.toLocaleString('en-IN')}<small>(Your Price)</small></strong><span>₹ {data.high.toLocaleString('en-IN')}</span></footer></div></section>}

function QualityDetails({product}){return <section className="product-lower-panel quality-panel"><DetailPanelTitle icon={ShieldCheck} title="Quality Details"/><dl>{product.detail.qualityDetails.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>}

function BatchInfo({product,status}){const info=product.detail.batchInfo;return <section className="product-lower-panel batch-panel"><DetailPanelTitle icon={FileIcon} title="Batch / Listing Information"/><dl><div><dt>Product ID</dt><dd>{info.productId}</dd><dt>Last Updated</dt><dd>{formatDate(info.lastUpdated)}</dd></div><div><dt>Batch Number</dt><dd>{info.batchNumber}</dd><dt>Quality Check</dt><dd>{info.qualityCheck}</dd></div><div><dt>Harvest Date</dt><dd>{formatDate(info.harvestDate)}</dd><dt>Status</dt><dd><span className={status}><i/>{status==='active'?'Active':'Inactive'}</span></dd></div><div><dt>Visibility</dt><dd>🌐 {info.visibility}</dd></div></dl></section>}
function FileIcon(){return <Box/>}

function StockModal({product,onClose}){const [value,setValue]=useState(product.detail.inventory.available);return <div className="product-modal" role="dialog" aria-modal="true" aria-label="Update stock"><div><button type="button" onClick={onClose} aria-label="Close"><X/></button><Package/><h3>Update {product.name} stock</h3><label>Available stock<input type="number" min="0" value={value} onChange={event=>setValue(event.target.value)}/><span>{product.detail.inventory.unit}</span></label><button type="button" onClick={onClose}>Save Stock</button></div></div>}

export default function FarmerProductDetails(){
  const {productId}=useParams(),navigate=useNavigate()
  const product=products.find(item=>String(item.id)===productId)
  const [imageIndex,setImageIndex]=useState(0),[expanded,setExpanded]=useState(false),[status,setStatus]=useState(product?.listingStatus||'inactive'),[stockOpen,setStockOpen]=useState(false)
  if(!product)return <><FarmerPageHero title="Product Details" subtitle="Manage and monitor your listed farm product." icon={Leaf} iconPlacement="end"/><div className="product-not-found"><Package/><h2>Product not found</h2><p>The requested product does not exist or may have been removed.</p><button type="button" onClick={()=>navigate('/farmer/products')}>Back to My Products</button></div></>
  return <><FarmerPageHero title="Product Details" subtitle="Manage and monitor your listed farm product." icon={Leaf} iconPlacement="end"/><div className="product-details-page"><div className="product-details-top"><section className="product-main-card"><div className="product-main-content"><ProductGallery product={product} imageIndex={imageIndex} setImageIndex={setImageIndex}/><ProductInfo product={product} status={status} expanded={expanded} setExpanded={setExpanded} onStock={()=>setStockOpen(true)} onToggle={()=>setStatus(value=>value==='active'?'inactive':'active')} navigate={navigate}/></div></section><ProductKeyFeatures/></div><div className="product-details-lower"><InventorySummary product={product}/><RecentOrders product={product}/><RatingsPanel product={product}/><PriceInsights product={product}/><QualityDetails product={product}/><BatchInfo product={product} status={status}/></div></div>{stockOpen&&<StockModal product={product} onClose={()=>setStockOpen(false)}/>}</>
}
