import { BadgeCheck, House, Leaf, MapPin, Pencil } from 'lucide-react'
import Card from '../../../../components/ui/Card'
import { farmOverviewFields, farmProfile } from '../data/myFarm.mock'

export default function FarmOverview() {
  return <Card className="min-w-0 p-4 xl:min-h-[360px] xl:flex xl:flex-col xl:justify-between">
    <div className="flex items-center justify-between gap-2"><h2 className="flex items-center gap-3 text-lg font-bold text-slate-900"><House className="size-7 fill-emerald-700 text-emerald-800" />Farm Overview</h2><button type="button" className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-1.5 text-xs text-slate-700 hover:bg-slate-50"><Pencil className="size-3.5 text-emerald-700" />Edit Profile</button></div>
    <div className="mt-3 flex min-w-0 items-center gap-4"><div className="h-[108px] w-[108px] shrink-0 rounded-lg bg-[url('/images/dashboard/farmer-hero.png')] bg-cover bg-center" role="img" aria-label="Shivam Kisan Farm" /><div className="min-w-0 flex-1"><h3 className="flex items-center gap-2 truncate text-lg font-bold text-slate-900"><Leaf className="size-6 shrink-0 fill-emerald-600 text-emerald-700" />{farmProfile.name}</h3><p className="mt-1 flex items-center gap-1.5 text-sm text-slate-600"><MapPin className="size-4 shrink-0" />{farmProfile.location}</p></div><div className="hidden shrink-0 text-right sm:block"><span className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-900"><BadgeCheck className="size-4 fill-emerald-700 text-white" />Verified Farmer</span><p className="mt-1 text-[11px] text-slate-500">Verified on {farmProfile.verifiedOn}</p></div></div>
    <div className="mt-3 grid gap-2 sm:grid-cols-3">{farmOverviewFields.map(({ label, key, icon: Icon }, index) => <div key={key} className={`flex min-w-0 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50/70 p-2.5 ${index === 3 ? 'sm:col-span-2' : ''}`}><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-emerald-50"><Icon className="size-6 fill-emerald-700/15 text-emerald-700" /></span><div className="min-w-0"><p className="text-[11px] text-slate-600">{label}</p><p className={`truncate text-sm font-semibold ${key === 'landRecord' ? 'text-emerald-800' : 'text-slate-900'}`}>{farmProfile[key]}</p></div></div>)}</div>
  </Card>
}
