import { ArrowRight, Leaf } from 'lucide-react'
import Card from '../../../../components/ui/Card'
import { cropPrices } from '../data/priceInsights.mock'

const demandTone = { High: 'bg-emerald-100 text-emerald-800', Medium: 'bg-amber-100 text-amber-800', Low: 'bg-red-100 text-red-700' }
const actionTone = { blue: 'bg-blue-100 text-blue-800', green: 'bg-emerald-100 text-emerald-800', orange: 'bg-orange-100 text-orange-800' }

export default function CropPriceComparison() {
  return <Card className="min-w-0 p-3 xl:min-h-[300px] xl:flex xl:flex-col xl:justify-between"><div className="flex items-center justify-between gap-2 px-1"><div><h2 className="flex items-center gap-2 text-base font-bold text-slate-900"><Leaf className="size-6 fill-emerald-700 text-emerald-700" />Crop Price Comparison</h2><p className="ml-8 text-xs text-slate-500">Real-time prices and market insights for key crops.</p></div><span className="inline-flex shrink-0 items-center gap-1 rounded-lg border border-emerald-200 px-2.5 py-1.5 text-xs font-medium text-emerald-800">View All Crops <ArrowRight className="size-4" /></span></div><div className="mt-2 overflow-x-auto rounded-lg border border-slate-200"><table className="w-full min-w-[680px] border-collapse text-left text-[11px]"><thead className="bg-slate-50 text-slate-700"><tr><th className="px-2 py-1 font-medium">Crop</th><th className="px-2 py-1 font-medium">Current Price<br />(₹ / quintal)</th><th className="px-2 py-1 font-medium">Last Week<br />(₹ / quintal)</th><th className="px-2 py-1 font-medium">Trend</th><th className="px-2 py-1 font-medium">Demand</th><th className="px-2 py-1 font-medium">Recommended Action</th></tr></thead><tbody>{cropPrices.map(row => <tr key={row.crop} className="h-[37px] border-t border-slate-200"><td className="whitespace-nowrap px-2 py-1"><span className="mr-2 text-base">{row.icon}</span>{row.crop}</td><td className="whitespace-nowrap px-2 py-1 font-semibold">₹ {row.current.toLocaleString('en-IN')}</td><td className="whitespace-nowrap px-2 py-1 text-slate-600">₹ {row.lastWeek.toLocaleString('en-IN')}</td><td className="px-2 py-1"><span className={`rounded-full px-2 py-1 font-semibold ${row.trend >= 0 ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-700'}`}>{row.trend >= 0 ? '↗ +' : '↘ '}{row.trend}%</span></td><td className="px-2 py-1"><span className={`rounded-full px-2 py-1 ${demandTone[row.demand]}`}>{row.demand}</span></td><td className="whitespace-nowrap px-2 py-1"><span className={`rounded-full px-2 py-1 ${actionTone[row.actionTone]}`}>{row.action}</span></td></tr>)}</tbody></table></div></Card>
}
